# Task 2 — Data Discovery, Profiling and Cleaning
**Project:** SkyPrint — Flight Tracking & Climate Impact Analysis

Inputs (from Task 1, `data/raw/`):
- latest `opensky_<timestamp>.json` — OpenSky state vectors from the Saudi-area extraction
- latest `openmeteo_<timestamp>.json` — weather for aircraft-relevant grid locations and pressure levels
- `aircraftDatabase.csv` — aircraft lookup (`plane_id` / ICAO24 → aircraft metadata and `typecode`)

This notebook keeps the same Task 2 methodology:
**Load → Flatten → Profile → Document issues → Clean → Save**

Outputs:
- `data/interim/cleaned_opensky.csv`
- `data/interim/cleaned_weather.csv`
- `data/interim/cleaned_aircraft.csv`

In [1]:
import pandas as pd
import numpy as np
import json
from pathlib import Path

# Resolve project paths safely
CWD = Path.cwd()
PROJECT_ROOT = CWD.parent if CWD.name == "notebooks" else CWD
RAW_DIR = PROJECT_ROOT / "data" / "raw"
INTERIM_DIR = PROJECT_ROOT / "data" / "interim"
INTERIM_DIR.mkdir(parents=True, exist_ok=True)
pd.set_option('display.max_columns', None)

def profile(df):
    rows = []
    for c in df.columns:
        s = df[c]
        sample = s.dropna().iloc[0] if s.notna().any() else None
        rows.append({'column': c, 'dtype': str(s.dtype), 'null_count': int(s.isna().sum()),
                     'percent_null': round(100 * s.isna().sum() / len(s), 2) if len(s) else 0,
                     'unique_count': int(s.nunique(dropna=True)), 'sample_value': sample})
    return pd.DataFrame(rows)

def raw_json_files(prefix):
    # Current layout plus legacy root-level files for backward compatibility.
    nested = sorted((RAW_DIR / prefix).glob('year=*/month=*/day=*/*.json'))
    legacy = sorted(RAW_DIR.glob(f'{prefix}_*.json'))
    files = nested + legacy
    if not files:
        fallback = RAW_DIR / f'{prefix}.json'
        if fallback.exists():
            files = [fallback]
    if not files:
        raise FileNotFoundError(f'No {prefix} JSON files found in {RAW_DIR}')
    return files

def batch_id_from_path(path, prefix):
    value = path.stem.removeprefix(f'{prefix}_')
    try:
        return pd.to_datetime(value, format='%Y-%m-%d_%H-%M-%S').strftime('%Y%m%d_%H%M%S')
    except (ValueError, TypeError):
        return value

## 1. OpenSky — Load and Flatten

`/states/all` returns a JSON object with `time` and a nested `states` list.
Task 1 uses `extended=1`, so each state vector has 18 fields including `category`.

In [2]:
opensky_files = raw_json_files('opensky')
print('OpenSky raw batches found:', len(opensky_files))
print('first:', opensky_files[0].relative_to(PROJECT_ROOT))
print('last :', opensky_files[-1].relative_to(PROJECT_ROOT))

OpenSky raw batches found: 4
first: data/raw/opensky/year=2026/month=09/day=21/opensky_20260921_234752.json
last : data/raw/opensky_2026-09-21_08-34-59.json

In [3]:
OPENSKY_COLUMNS = [
    'plane_id', 'flight_id', 'origin_country', 'time_position', 'last_contact',
    'longitude', 'latitude', 'baro_altitude', 'on_ground', 'velocity',
    'true_track', 'vertical_rate', 'sensors', 'geo_altitude', 'squawk',
    'spi', 'source_type', 'category'
]

sky_frames = []
for opensky_path in opensky_files:
    with open(opensky_path, encoding='utf-8') as f:
        opensky_raw = json.load(f)
    states = opensky_raw.get('states', []) or []
    state_lengths = pd.Series([len(row) for row in states]).value_counts().sort_index()
    if len(state_lengths) and not (len(state_lengths) == 1 and state_lengths.index[0] == 18):
        raise ValueError(f'Unexpected OpenSky state-vector length in {opensky_path}. Expected 18 fields.')
    frame = pd.DataFrame(states, columns=OPENSKY_COLUMNS)
    frame['batch_id'] = batch_id_from_path(opensky_path, 'opensky')
    frame['source_file'] = str(opensky_path.relative_to(PROJECT_ROOT))
    sky_frames.append(frame)
    print('loaded:', opensky_path.name, '| rows:', len(frame))

df_sky = pd.concat(sky_frames, ignore_index=True)
print('combined shape:', df_sky.shape)
df_sky.head()

loaded: opensky_20260921_234752.json | rows: 108
loaded: opensky_20260921_235027.json | rows: 111
loaded: opensky_2026-09-20_05-41-21.json | rows: 163
loaded: opensky_2026-09-21_08-34-59.json | rows: 103
combined shape: (485, 20)

,plane_id,flight_id,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,sensors,geo_altitude,squawk,spi,source_type,category,batch_id,source_file
0,801619,IGO1423,India,1790023666,1790023666,55.8897,25.2288,1493.52,False,133.28,268.67,-6.50,None,1562.10,NaN,False,0,0,20260921_234752,data/raw/opensky/year=2026/month=09/day=21/ope...
1,801673,AXB814,India,1790023666,1790023666,55.1700,25.1996,1813.56,False,138.02,164.88,6.50,None,1874.52,6203,False,0,0,20260921_234752,data/raw/opensky/year=2026/month=09/day=21/ope...
2,80169c,IGO1326,India,1790023533,1790023534,54.0266,21.8863,11887.20,False,230.88,96.40,-0.33,None,12641.58,2150,False,0,0,20260921_234752,data/raw/opensky/year=2026/month=09/day=21/ope...
3,778823,FYC728,Syrian Arab Republic,1790023644,1790023666,48.5936,27.4207,10355.58,False,232.35,299.01,0.33,None,11064.24,6233,False,0,0,20260921_234752,data/raw/opensky/year=2026/month=09/day=21/ope...
4,8015e5,IGO38E,India,1790023665,1790023665,54.9076,24.4297,3893.82,False,179.84,122.14,12.68,None,4130.04,3451,False,0,0,20260921_234752,data/raw/opensky/year=2026/month=09/day=21/ope...

## 2. OpenSky — Profiling

In [4]:
profile_sky = profile(df_sky)
profile_sky

,column,dtype,null_count,percent_null,unique_count,sample_value
0,plane_id,str,0,0.00,355,801619
1,flight_id,str,0,0.00,366,IGO1423
2,origin_country,str,0,0.00,34,India
3,time_position,int64,0,0.00,188,1790023666
4,last_contact,int64,0,0.00,133,1790023666
5,longitude,float64,0,0.00,454,55.8897
6,latitude,float64,0,0.00,457,25.2288
7,baro_altitude,float64,29,5.98,271,1493.52
8,on_ground,bool,0,0.00,2,False
9,velocity,float64,0,0.00,442,133.28
10,true_track,float64,0,0.00,439,268.67
11,vertical_rate,float64,31,6.39,84,-6.5
12,sensors,object,485,100.00,0,None
13,geo_altitude,float64,44,9.07,320,1562.1
14,squawk,str,73,15.05,299,6203
15,spi,bool,0,0.00,2,False
16,source_type,int64,0,0.00,1,0
17,category,int64,0,0.00,4,0
18,batch_id,str,0,0.00,4,20260921_234752
19,source_file,str,0,0.00,4,data/raw/opensky/year=2026/month=09/day=21/ope...

In [5]:
print('rows:', len(df_sky), ' columns:', df_sky.shape[1])
print('exact duplicate rows:', df_sky.duplicated().sum())
print('duplicate (batch_id, plane_id, time_position) rows:',
      df_sky.duplicated(subset=['batch_id', 'plane_id', 'time_position']).sum())

flight_text = df_sky['flight_id'].astype('string')
print('empty-string flight_ids:', (flight_text.str.strip() == '').sum())
print('missing positions:', df_sky[['latitude', 'longitude']].isna().any(axis=1).sum())
print('category value counts:')
print(df_sky['category'].value_counts(dropna=False).sort_index())

rows: 485  columns: 20
exact duplicate rows: 0
duplicate (batch_id, plane_id, time_position) rows: 0
empty-string flight_ids: 12
missing positions: 0
category value counts:
category
0    468
1      6
2      2
6      9
Name: count, dtype: int64

### Issues found — OpenSky

| # | Issue | Decision |
|---|---|---|
| 1 | `sensors` is not useful for this project and is commonly null in this endpoint | Drop |
| 2 | `flight_id` may contain fixed-width trailing spaces or empty strings | Strip whitespace; empty → missing |
| 3 | Position/time/altitude fields can legitimately be missing in a live state vector | Keep missing values; do not invent/impute flight data |
| 4 | `squawk` and `spi` are operational fields not needed for SkyPrint fuel/trajectory analysis | Drop from cleaned analytical file; raw JSON remains unchanged |
| 5 | Unix timestamps are not analysis-friendly | Convert to UTC datetime |
| 6 | Future repeated pulls can create duplicate aircraft observations | Deduplicate on (`plane_id`, `time_position`) |
| 7 | `plane_id` is the ICAO24 join key | Normalize to lowercase and trim whitespace |
| 8 | `category` is available because Task 1 uses `extended=1` | Keep |

## 3. OpenSky — Cleaning

In [6]:
df_sky_clean = df_sky.copy()

# 1) Remove columns outside the analytical scope.
df_sky_clean = df_sky_clean.drop(columns=['sensors', 'squawk', 'spi'])

# 2) Standardize identifiers/text.
df_sky_clean['plane_id'] = (
    df_sky_clean['plane_id'].astype('string').str.strip().str.lower()
)
df_sky_clean['flight_id'] = (
    df_sky_clean['flight_id'].astype('string').str.strip().replace('', pd.NA)
)
df_sky_clean['origin_country'] = (
    df_sky_clean['origin_country'].astype('string').str.strip().replace('', pd.NA)
)

# 3) Convert Unix epoch seconds to UTC datetimes.
for col in ['time_position', 'last_contact']:
    df_sky_clean[col] = pd.to_datetime(
        df_sky_clean[col], unit='s', utc=True, errors='coerce'
    )

# 4) Explicit dtypes.
df_sky_clean['on_ground'] = df_sky_clean['on_ground'].astype('boolean')
df_sky_clean['category'] = pd.to_numeric(df_sky_clean['category'], errors='coerce').astype('Int64')
df_sky_clean['source_type'] = pd.to_numeric(df_sky_clean['source_type'], errors='coerce').astype('Int64')

# 5) Deduplicate the observation natural key.
before = len(df_sky_clean)
df_sky_clean = df_sky_clean.drop_duplicates(subset=['batch_id', 'plane_id', 'time_position'])
print(f'dropped {before - len(df_sky_clean)} duplicate OpenSky observations')

df_sky_clean.dtypes

dropped 0 duplicate OpenSky observations

plane_id                      string
flight_id                     string
origin_country                string
time_position     datetime64[s, UTC]
last_contact      datetime64[s, UTC]
longitude                    float64
latitude                     float64
baro_altitude                float64
on_ground                    boolean
velocity                     float64
true_track                   float64
vertical_rate                float64
geo_altitude                 float64
source_type                    Int64
category                       Int64
batch_id                         str
source_file                      str
dtype: object

In [7]:
df_sky_clean.head()

,plane_id,flight_id,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,geo_altitude,source_type,category,batch_id,source_file
0,801619,IGO1423,India,2026-09-21 20:47:46+00:00,2026-09-21 20:47:46+00:00,55.8897,25.2288,1493.52,False,133.28,268.67,-6.50,1562.10,0,0,20260921_234752,data/raw/opensky/year=2026/month=09/day=21/ope...
1,801673,AXB814,India,2026-09-21 20:47:46+00:00,2026-09-21 20:47:46+00:00,55.1700,25.1996,1813.56,False,138.02,164.88,6.50,1874.52,0,0,20260921_234752,data/raw/opensky/year=2026/month=09/day=21/ope...
2,80169c,IGO1326,India,2026-09-21 20:45:33+00:00,2026-09-21 20:45:34+00:00,54.0266,21.8863,11887.20,False,230.88,96.40,-0.33,12641.58,0,0,20260921_234752,data/raw/opensky/year=2026/month=09/day=21/ope...
3,778823,FYC728,Syrian Arab Republic,2026-09-21 20:47:24+00:00,2026-09-21 20:47:46+00:00,48.5936,27.4207,10355.58,False,232.35,299.01,0.33,11064.24,0,0,20260921_234752,data/raw/opensky/year=2026/month=09/day=21/ope...
4,8015e5,IGO38E,India,2026-09-21 20:47:45+00:00,2026-09-21 20:47:45+00:00,54.9076,24.4297,3893.82,False,179.84,122.14,12.68,4130.04,0,0,20260921_234752,data/raw/opensky/year=2026/month=09/day=21/ope...

In [8]:
sky_output = INTERIM_DIR / 'cleaned_opensky.csv'
df_sky_clean.to_csv(sky_output, index=False)
print('saved:', sky_output.resolve())

saved: /Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/data/interim/cleaned_opensky.csv

## 4. Open-Meteo — Load and Flatten

The new extraction can request **multiple aircraft-relevant locations** in one call.
Open-Meteo therefore returns either:
- one forecast object (single location), or
- a list of forecast objects (multiple locations).

Each forecast object contains hourly parallel arrays. We flatten every location and preserve its latitude/longitude.

In [9]:
meteo_files = raw_json_files('openmeteo')
print('Open-Meteo raw batches found:', len(meteo_files))
print('first:', meteo_files[0].relative_to(PROJECT_ROOT))
print('last :', meteo_files[-1].relative_to(PROJECT_ROOT))

Open-Meteo raw batches found: 4
first: data/raw/openmeteo/year=2026/month=09/day=21/openmeteo_20260921_234752.json
last : data/raw/openmeteo_2026-09-21_08-34-59.json

In [10]:
weather_frames = []

for meteo_path in meteo_files:
    with open(meteo_path, encoding='utf-8') as f:
        meteo_raw = json.load(f)
    meteo_locations = meteo_raw if isinstance(meteo_raw, list) else [meteo_raw]
    batch_id = batch_id_from_path(meteo_path, 'openmeteo')

    for location_index, location in enumerate(meteo_locations):
        hourly = location.get('hourly', {})
        if not hourly or 'time' not in hourly:
            continue
        frame = pd.DataFrame(hourly)
        frame['latitude'] = location.get('latitude')
        frame['longitude'] = location.get('longitude')
        frame['elevation_m'] = location.get('elevation')
        # Open-Meteo may not provide location_id; fallback is unique within this batch.
        frame['location_id'] = location.get('location_id', location_index)
        frame['timezone'] = location.get('timezone')
        frame['batch_id'] = batch_id
        frame['source_file'] = str(meteo_path.relative_to(PROJECT_ROOT))
        weather_frames.append(frame)

    print('loaded:', meteo_path.name, '| locations:', len(meteo_locations))

if not weather_frames:
    raise ValueError('No hourly weather data found in the Open-Meteo raw responses.')

df_wx = pd.concat(weather_frames, ignore_index=True)
print('combined shape:', df_wx.shape)
print('unique batches:', df_wx['batch_id'].nunique())
print('unique weather coordinates:', df_wx[['batch_id', 'latitude', 'longitude']].drop_duplicates().shape[0])
df_wx.head()

loaded: openmeteo_20260921_234752.json | locations: 94
loaded: openmeteo_20260921_235027.json | locations: 94
loaded: openmeteo_2026-09-20_05-41-21.json | locations: 150
loaded: openmeteo_2026-09-21_08-34-59.json | locations: 89
combined shape: (10248, 32)
unique batches: 4
unique weather coordinates: 419

,time,temperature_850hPa,wind_speed_850hPa,wind_direction_850hPa,geopotential_height_850hPa,temperature_700hPa,wind_speed_700hPa,wind_direction_700hPa,geopotential_height_700hPa,temperature_500hPa,wind_speed_500hPa,wind_direction_500hPa,geopotential_height_500hPa,temperature_300hPa,wind_speed_300hPa,wind_direction_300hPa,geopotential_height_300hPa,temperature_250hPa,wind_speed_250hPa,wind_direction_250hPa,geopotential_height_250hPa,temperature_200hPa,wind_speed_200hPa,wind_direction_200hPa,geopotential_height_200hPa,latitude,longitude,elevation_m,location_id,timezone,batch_id,source_file
0,2026-09-21T00:00,29.0,17.7,305,1532.0,13.8,11.2,19,3210.0,-5.4,22.4,74,5929.0,-31.5,3.4,315,9761.29,-41.0,12.4,209,11024.76,-52.0,35.4,208,12504.65,25.202108,55.885532,151.0,0,GMT,20260921_234752,data/raw/openmeteo/year=2026/month=09/day=21/o...
1,2026-09-21T01:00,29.0,19.2,306,1531.0,13.8,12.2,15,3209.0,-5.4,21.3,74,5927.0,-31.5,3.4,315,9756.45,-41.0,13.0,214,11020.95,-52.5,36.0,210,12500.00,25.202108,55.885532,151.0,0,GMT,20260921_234752,data/raw/openmeteo/year=2026/month=09/day=21/o...
2,2026-09-21T02:00,28.8,19.9,307,1533.0,13.8,13.8,8,3211.0,-5.6,20.5,69,5927.0,-31.5,5.1,315,9756.45,-41.0,13.0,214,11019.05,-52.5,35.6,213,12497.67,25.202108,55.885532,151.0,0,GMT,20260921_234752,data/raw/openmeteo/year=2026/month=09/day=21/o...
3,2026-09-21T03:00,28.6,21.1,307,1538.0,14.0,14.9,360,3216.0,-5.6,21.0,66,5932.0,-31.5,4.3,326,9758.06,-41.0,13.4,207,11020.95,-52.5,36.6,212,12500.00,25.202108,55.885532,151.0,0,GMT,20260921_234752,data/raw/openmeteo/year=2026/month=09/day=21/o...
4,2026-09-21T04:00,28.6,22.7,308,1545.0,14.0,15.6,353,3222.0,-5.4,20.4,62,5938.0,-31.5,4.3,326,9764.52,-41.0,15.2,198,11026.67,-52.5,38.3,212,12504.65,25.202108,55.885532,151.0,0,GMT,20260921_234752,data/raw/openmeteo/year=2026/month=09/day=21/o...

In [11]:
print("Weather batches:", df_wx['batch_id'].nunique())
print("Weather location keys:", df_wx[['batch_id', 'location_id']].drop_duplicates().shape[0])
print("Unique returned coordinates across batches:", df_wx[['latitude', 'longitude']].drop_duplicates().shape[0])

Weather batches: 4
Weather location keys: 427
Unique returned coordinates across batches: 351

## 5. Open-Meteo — Profiling

In [12]:
profile_wx = profile(df_wx)
profile_wx

,column,dtype,null_count,percent_null,unique_count,sample_value
0,time,str,0,0.0,48,2026-09-21T00:00
1,temperature_850hPa,float64,0,0.0,152,29.0
2,wind_speed_850hPa,float64,0,0.0,434,17.7
3,wind_direction_850hPa,int64,0,0.0,356,305
4,geopotential_height_850hPa,float64,0,0.0,55,1532.0
5,temperature_700hPa,float64,0,0.0,49,13.8
6,wind_speed_700hPa,float64,0,0.0,496,11.2
7,wind_direction_700hPa,int64,0,0.0,344,19
8,geopotential_height_700hPa,float64,0,0.0,91,3210.0
9,temperature_500hPa,float64,0,0.0,31,-5.4
10,wind_speed_500hPa,float64,0,0.0,417,22.4
11,wind_direction_500hPa,int64,0,0.0,314,74
12,geopotential_height_500hPa,float64,0,0.0,87,5929.0
13,temperature_300hPa,float64,0,0.0,16,-31.5
14,wind_speed_300hPa,float64,0,0.0,545,3.4
15,wind_direction_300hPa,int64,0,0.0,341,315
16,geopotential_height_300hPa,float64,0,0.0,103,9761.29
17,temperature_250hPa,float64,0,0.0,19,-41.0
18,wind_speed_250hPa,float64,0,0.0,577,12.4
19,wind_direction_250hPa,int64,0,0.0,319,209
20,geopotential_height_250hPa,float64,0,0.0,96,11024.76
21,temperature_200hPa,float64,0,0.0,18,-52.0
22,wind_speed_200hPa,float64,0,0.0,628,35.4
23,wind_direction_200hPa,int64,0,0.0,260,208
24,geopotential_height_200hPa,float64,0,0.0,83,12504.65
25,latitude,float64,0,0.0,98,25.202108
26,longitude,float64,0,0.0,327,55.885532
27,elevation_m,float64,0,0.0,168,151.0
28,location_id,int64,0,0.0,150,0
29,timezone,str,0,0.0,1,GMT
30,batch_id,str,0,0.0,4,20260921_234752
31,source_file,str,0,0.0,4,data/raw/openmeteo/year=2026/month=09/day=21/o...

In [13]:
print('rows:', len(df_wx))
print('exact duplicate rows:', df_wx.duplicated().sum())
print('unique locations:', df_wx[['latitude', 'longitude']].drop_duplicates().shape[0])
print('duplicate (batch, location, time) rows:',
      df_wx.duplicated(subset=['batch_id', 'latitude', 'longitude', 'time']).sum())
print('missing timestamps:', df_wx['time'].isna().sum())

# Show all rows involved in duplicated location + time keys
weather_dup_mask = df_wx.duplicated(
    subset=['batch_id', 'latitude', 'longitude', 'time'],
    keep=False
)

weather_duplicates = (
    df_wx[weather_dup_mask]
    .sort_values(['batch_id', 'latitude', 'longitude', 'time'])
)

print("Rows involved in duplicates:", len(weather_duplicates))
print(
    "Duplicated location/time groups:",
    weather_duplicates.groupby(
        ['batch_id', 'latitude', 'longitude', 'time']
    ).ngroups
)

weather_duplicates

rows: 10248
exact duplicate rows: 0
unique locations: 351
duplicate (batch, location, time) rows: 192
missing timestamps: 0
Rows involved in duplicates: 360
Duplicated location/time groups: 168

,time,temperature_850hPa,wind_speed_850hPa,wind_direction_850hPa,geopotential_height_850hPa,temperature_700hPa,wind_speed_700hPa,wind_direction_700hPa,geopotential_height_700hPa,temperature_500hPa,wind_speed_500hPa,wind_direction_500hPa,geopotential_height_500hPa,temperature_300hPa,wind_speed_300hPa,wind_direction_300hPa,geopotential_height_300hPa,temperature_250hPa,wind_speed_250hPa,wind_direction_250hPa,geopotential_height_250hPa,temperature_200hPa,wind_speed_200hPa,wind_direction_200hPa,geopotential_height_200hPa,latitude,longitude,elevation_m,location_id,timezone,batch_id,source_file
7536,2026-09-20T00:00,26.9,11.6,225,1516.0,15.4,12.7,79,3192.0,-4.9,8.7,106,5940.0,-30.0,29.0,204,9767.74,-41.5,29.6,212,11034.29,-52.5,29.0,218,12509.30,25.272406,51.567566,0.0,126,GMT,20260920_054121,data/raw/openmeteo_2026-09-20_05-41-21.json
7992,2026-09-20T00:00,26.9,11.6,225,1516.0,15.4,12.7,79,3192.0,-4.9,8.7,106,5940.0,-30.0,29.0,204,9767.74,-41.5,29.6,212,11034.29,-52.5,29.0,218,12509.30,25.272406,51.567566,0.0,145,GMT,20260920_054121,data/raw/openmeteo_2026-09-20_05-41-21.json
7537,2026-09-20T01:00,26.8,13.7,217,1520.0,15.2,14.9,92,3196.0,-4.9,7.2,90,5943.0,-30.0,32.2,207,9770.97,-41.5,29.3,215,11036.19,-52.5,28.1,220,12511.63,25.272406,51.567566,0.0,126,GMT,20260920_054121,data/raw/openmeteo_2026-09-20_05-41-21.json
7993,2026-09-20T01:00,26.8,13.7,217,1520.0,15.2,14.9,92,3196.0,-4.9,7.2,90,5943.0,-30.0,32.2,207,9770.97,-41.5,29.3,215,11036.19,-52.5,28.1,220,12511.63,25.272406,51.567566,0.0,145,GMT,20260920_054121,data/raw/openmeteo_2026-09-20_05-41-21.json
7538,2026-09-20T02:00,26.8,16.2,212,1520.0,15.2,18.4,102,3195.0,-4.9,8.7,74,5943.0,-30.5,32.8,208,9769.35,-41.5,27.4,218,11034.29,-52.5,27.2,221,12509.30,25.272406,51.567566,0.0,126,GMT,20260920_054121,data/raw/openmeteo_2026-09-20_05-41-21.json
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3909,2026-09-21T21:00,29.1,21.8,349,1531.0,14.6,16.1,23,3213.0,-5.8,14.4,42,5932.0,-32.5,30.1,185,9756.45,-42.5,32.6,197,11013.33,-52.5,55.8,208,12488.37,25.272406,51.567566,0.0,68,GMT,20260921_235027,data/raw/openmeteo/year=2026/month=09/day=21/o...
2686,2026-09-21T22:00,29.2,26.5,4,1531.0,14.5,16.3,18,3212.0,-6.1,13.7,38,5930.0,-32.5,28.9,185,9753.23,-42.5,30.4,198,11009.53,-52.5,52.3,212,12486.05,25.272406,51.567566,6.0,17,GMT,20260921_235027,data/raw/openmeteo/year=2026/month=09/day=21/o...
3910,2026-09-21T22:00,29.2,26.5,4,1531.0,14.5,16.3,18,3212.0,-6.1,13.7,38,5930.0,-32.5,28.9,185,9753.23,-42.5,30.4,198,11009.53,-52.5,52.3,212,12486.05,25.272406,51.567566,0.0,68,GMT,20260921_235027,data/raw/openmeteo/year=2026/month=09/day=21/o...
2687,2026-09-21T23:00,29.3,31.7,16,1529.0,14.3,20.8,10,3210.0,-6.1,12.8,41,5927.0,-32.5,26.4,183,9750.00,-42.5,28.5,202,11005.72,-52.5,49.9,215,12481.40,25.272406,51.567566,6.0,17,GMT,20260921_235027,data/raw/openmeteo/year=2026/month=09/day=21/o...
3911,2026-09-21T23:00,29.3,31.7,16,1529.0,14.3,20.8,10,3210.0,-6.1,12.8,41,5927.0,-32.5,26.4,183,9750.00,-42.5,28.5,202,11005.72,-52.5,49.9,215,12481.40,25.272406,51.567566,0.0,68,GMT,20260921_235027,data/raw/openmeteo/year=2026/month=09/day=21/o...

### Issues found — Open-Meteo

| # | Issue | Decision |
|---|---|---|
| 1 | New raw response contains multiple locations rather than the old single Riyadh point | Flatten every returned location |
| 2 | Hourly weather is stored as parallel arrays | Convert each location's `hourly` block to rows |
| 3 | `time` is text | Convert to UTC datetime |
| 4 | The same hour can appear at many locations, and repeated location/time keys may contain different weather values | Keep repeated (`latitude`, `longitude`, `time`) rows when weather values differ; remove only exact duplicate rows |
| 5 | Pressure-level variable names already encode the atmospheric level (`850hPa`, `700hPa`, etc.) | Keep them as separate columns for later aircraft-altitude matching |
| 6 | Missing weather values should not be guessed | Keep as missing; Task 3 validates them |

## 6. Open-Meteo — Cleaning

In [14]:
df_wx_clean = df_wx.copy()

# 1) Convert time to UTC and give it an analysis-friendly name.
df_wx_clean['time'] = pd.to_datetime(df_wx_clean['time'], utc=True, errors='coerce')
df_wx_clean = df_wx_clean.rename(columns={'time': 'observation_time'})

# 2) Ensure coordinates/elevation and weather measurements are numeric.
non_numeric_weather = {'observation_time', 'timezone', 'batch_id', 'source_file'}
for col in df_wx_clean.columns:
    if col not in non_numeric_weather:
        df_wx_clean[col] = pd.to_numeric(df_wx_clean[col], errors='coerce')

# 3) Remove only true duplicates for the same location and hour.
# Do not drop rows only because returned latitude/longitude/time match.
# Some requested locations can map to the same Open-Meteo grid coordinates
# while retaining different location metadata.

exact_duplicates = df_wx_clean.duplicated().sum()

print("Exact duplicate weather rows:", exact_duplicates)

if exact_duplicates > 0:
    df_wx_clean = df_wx_clean.drop_duplicates()

print("Weather rows after cleaning:", len(df_wx_clean))

Exact duplicate weather rows: 0
Weather rows after cleaning: 10248

In [15]:
df_wx_clean.head()

,observation_time,temperature_850hPa,wind_speed_850hPa,wind_direction_850hPa,geopotential_height_850hPa,temperature_700hPa,wind_speed_700hPa,wind_direction_700hPa,geopotential_height_700hPa,temperature_500hPa,wind_speed_500hPa,wind_direction_500hPa,geopotential_height_500hPa,temperature_300hPa,wind_speed_300hPa,wind_direction_300hPa,geopotential_height_300hPa,temperature_250hPa,wind_speed_250hPa,wind_direction_250hPa,geopotential_height_250hPa,temperature_200hPa,wind_speed_200hPa,wind_direction_200hPa,geopotential_height_200hPa,latitude,longitude,elevation_m,location_id,timezone,batch_id,source_file
0,2026-09-21 00:00:00+00:00,29.0,17.7,305,1532.0,13.8,11.2,19,3210.0,-5.4,22.4,74,5929.0,-31.5,3.4,315,9761.29,-41.0,12.4,209,11024.76,-52.0,35.4,208,12504.65,25.202108,55.885532,151.0,0,GMT,20260921_234752,data/raw/openmeteo/year=2026/month=09/day=21/o...
1,2026-09-21 01:00:00+00:00,29.0,19.2,306,1531.0,13.8,12.2,15,3209.0,-5.4,21.3,74,5927.0,-31.5,3.4,315,9756.45,-41.0,13.0,214,11020.95,-52.5,36.0,210,12500.00,25.202108,55.885532,151.0,0,GMT,20260921_234752,data/raw/openmeteo/year=2026/month=09/day=21/o...
2,2026-09-21 02:00:00+00:00,28.8,19.9,307,1533.0,13.8,13.8,8,3211.0,-5.6,20.5,69,5927.0,-31.5,5.1,315,9756.45,-41.0,13.0,214,11019.05,-52.5,35.6,213,12497.67,25.202108,55.885532,151.0,0,GMT,20260921_234752,data/raw/openmeteo/year=2026/month=09/day=21/o...
3,2026-09-21 03:00:00+00:00,28.6,21.1,307,1538.0,14.0,14.9,360,3216.0,-5.6,21.0,66,5932.0,-31.5,4.3,326,9758.06,-41.0,13.4,207,11020.95,-52.5,36.6,212,12500.00,25.202108,55.885532,151.0,0,GMT,20260921_234752,data/raw/openmeteo/year=2026/month=09/day=21/o...
4,2026-09-21 04:00:00+00:00,28.6,22.7,308,1545.0,14.0,15.6,353,3222.0,-5.4,20.4,62,5938.0,-31.5,4.3,326,9764.52,-41.0,15.2,198,11026.67,-52.5,38.3,212,12504.65,25.202108,55.885532,151.0,0,GMT,20260921_234752,data/raw/openmeteo/year=2026/month=09/day=21/o...

In [16]:
weather_output = INTERIM_DIR / 'cleaned_weather.csv'
df_wx_clean.to_csv(weather_output, index=False)
print('saved:', weather_output.resolve())

saved: /Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/data/interim/cleaned_weather.csv

## 7. Aircraft Type Lookup — Load and Profile

The aircraft database is a reference dataset. Its `icao24` is renamed to `plane_id` so it can later join to OpenSky.

**Important for SkyPrint:** `typecode` will later determine whether an aircraft type can be mapped to the fuel/performance model.  
We therefore clean `plane_id` and `typecode` carefully before resolving duplicate `plane_id` records.

In [17]:
df_ac = pd.read_csv(RAW_DIR / 'aircraftDatabase.csv', dtype='string')
df_ac = df_ac.rename(columns={'icao24': 'plane_id'})

print('shape:', df_ac.shape)
df_ac.head(3)

shape: (520000, 27)

,plane_id,registration,manufacturericao,manufacturername,model,typecode,serialnumber,linenumber,icaoaircrafttype,operator,operatorcallsign,operatoricao,operatoriata,owner,testreg,registered,reguntil,status,built,firstflightdate,seatconfiguration,engines,modes,adsb,acars,notes,categoryDescription
0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,false,false,false,<NA>,<NA>
1,aa3487,N757F,RAYTHEON,Raytheon Aircraft Company,A36,BE36,E-3121,<NA>,L1P,<NA>,<NA>,<NA>,<NA>,Vintage Aircraft Llc,<NA>,<NA>,2027-01-31,<NA>,<NA>,<NA>,<NA>,<NA>,false,false,false,<NA>,<NA>
2,a4fa61,N42MH,PIPER,Piper,PA-31-350,PA31,31-7852015,<NA>,L2P,<NA>,<NA>,<NA>,<NA>,Tvpx Aircraft Solutions Inc Trustee,<NA>,<NA>,2029-08-31,<NA>,1977-01-01,<NA>,<NA>,LYCOMING TI0-540 SER,false,false,false,<NA>,<NA>

In [18]:
profile_ac = profile(df_ac)
profile_ac

,column,dtype,null_count,percent_null,unique_count,sample_value
0,plane_id,string,1,0.00,519997,aa3487
1,registration,string,3474,0.67,514254,N757F
2,manufacturericao,string,91199,17.54,739,RAYTHEON
3,manufacturername,string,81434,15.66,41540,Raytheon Aircraft Company
4,model,string,79574,15.30,34482,A36
5,typecode,string,40053,7.70,1933,BE36
6,serialnumber,string,82882,15.94,295525,E-3121
7,linenumber,string,519029,99.81,693,AF1085
8,icaoaircrafttype,string,91216,17.54,51,L1P
9,operator,string,496302,95.44,4001,Indian Air Force
10,operatorcallsign,string,479910,92.29,1650,INDIAN AIRFORCE
11,operatoricao,string,478598,92.04,1706,IFC
12,operatoriata,string,511934,98.45,511,DL
13,owner,string,84087,16.17,224893,Vintage Aircraft Llc
14,testreg,string,519703,99.94,227,D-AVYR
15,registered,string,457083,87.90,11139,2000-09-22
16,reguntil,string,248094,47.71,2035,2027-01-31
17,status,string,520000,100.00,0,NaN
18,built,string,263364,50.65,381,1977-01-01
19,firstflightdate,string,519680,99.94,273,1999-03-05
20,seatconfiguration,string,520000,100.00,0,NaN
21,engines,string,242178,46.57,7529,LYCOMING TI0-540 SER
22,modes,string,0,0.00,1,false
23,adsb,string,0,0.00,1,false
24,acars,string,0,0.00,1,false
25,notes,string,519660,99.93,264,Was RAAF A23-046
26,categoryDescription,string,512795,98.61,14,Large (75000 to 300000 lbs)

In [19]:
null_pct = (df_ac.isna().sum() / len(df_ac) * 100).round(2).sort_values(ascending=False)

print('rows with plane_id null:', df_ac['plane_id'].isna().sum())
print('exact duplicate rows:', df_ac.duplicated().sum())
print('duplicate plane_id rows (before normalization):',
      df_ac[df_ac['plane_id'].notna()].duplicated(subset=['plane_id']).sum())
print('typecode nulls:', df_ac['typecode'].isna().sum())
print()
print('columns with >= 90% nulls:')
print(null_pct[null_pct >= 90])

rows with plane_id null: 1
exact duplicate rows: 2
duplicate plane_id rows (before normalization): 2
typecode nulls: 40053

columns with >= 90% nulls:
status                 100.00
seatconfiguration      100.00
firstflightdate         99.94
testreg                 99.94
notes                   99.93
linenumber              99.81
categoryDescription     98.61
operatoriata            98.45
operator                95.44
operatorcallsign        92.29
operatoricao            92.04
dtype: float64

### Issues found — Aircraft Database

| # | Issue | Decision |
|---|---|---|
| 1 | Rows without `plane_id` cannot join to OpenSky | Drop |
| 2 | `plane_id` may differ only by case/whitespace | Trim + lowercase before duplicate checks |
| 3 | `typecode` may differ only by case/whitespace (for example `b738`, `B738 `) | Trim + uppercase before comparing |
| 4 | Blank-like text can look like a real value | Convert empty/`nan`/`none`/`null` text to missing |
| 5 | Duplicate `plane_id` rows may contain the same useful `typecode` plus missing values | Treat as one aircraft; keep the one normalized non-null typecode |
| 6 | Duplicate `plane_id` rows may contain genuinely different non-null `typecode`s | Do **not** guess; set `typecode` missing and `typecode_status = conflict` |
| 7 | A `plane_id` with no usable `typecode` | Keep aircraft row with `typecode_status = missing` |
| 8 | Some columns are zero-variance or ≥90% null and were already out of project scope | Keep the team's existing fixed drop list |
| 9 | `built`, `registered`, `reguntil` are date text | Convert to datetime |

## 8. Aircraft Type Lookup — Cleaning

In [20]:
df_ac_clean = df_ac.copy()

# 1) Normalize missing plane IDs, then remove rows that cannot join to OpenSky.
df_ac_clean['plane_id'] = (
    df_ac_clean['plane_id']
    .astype('string')
    .str.strip()
    .str.lower()
    .replace({'': pd.NA, 'nan': pd.NA, 'none': pd.NA, 'null': pd.NA})
)
df_ac_clean = df_ac_clean.dropna(subset=['plane_id'])

# 2) Normalize typecode BEFORE deciding whether duplicate plane IDs conflict.
# We intentionally normalize case/whitespace only; we do not remove punctuation blindly.
df_ac_clean['typecode'] = (
    df_ac_clean['typecode']
    .astype('string')
    .str.strip()
    .str.upper()
    .replace({'': pd.NA, 'NAN': pd.NA, 'NONE': pd.NA, 'NULL': pd.NA})
)



# 3) Drop exact duplicates after normalization.
before = len(df_ac_clean)
df_ac_clean = df_ac_clean.drop_duplicates()
print(f'dropped {before - len(df_ac_clean)} exact duplicate aircraft rows after normalization')

# 4) Drop columns that are clearly unusable/out of scope for this project.
cols_to_drop = [
    'modes', 'adsb', 'acars',
    'status', 'seatconfiguration', 'firstflightdate',
    'testreg', 'notes', 'linenumber',
    'operatoriata', 'operatorcallsign'
]

cols_to_drop = [c for c in cols_to_drop if c in df_ac_clean.columns]
df_ac_clean = df_ac_clean.drop(columns=cols_to_drop)

# 5) Parse date-like text columns that survived.
for col in ['built', 'registered', 'reguntil']:
    if col in df_ac_clean.columns:
        df_ac_clean[col] = pd.to_datetime(df_ac_clean[col], errors='coerce')

dropped 2 exact duplicate aircraft rows after normalization

In [21]:
# Inspect duplicate plane_ids AFTER normalization and count distinct usable typecodes.
typecodes_per_plane = (
    df_ac_clean.groupby('plane_id')['typecode']
    .agg(lambda s: sorted(set(s.dropna())))
)

duplicate_plane_ids = df_ac_clean.loc[
    df_ac_clean.duplicated('plane_id', keep=False), 'plane_id'
].unique()

print('duplicate plane_ids after normalization:', len(duplicate_plane_ids))

duplicate_typecode_summary = pd.DataFrame({
    'plane_id': typecodes_per_plane.index,
    'unique_non_null_typecodes': typecodes_per_plane.values
})
duplicate_typecode_summary['typecode_count'] = (
    duplicate_typecode_summary['unique_non_null_typecodes'].str.len()
)
duplicate_typecode_summary = duplicate_typecode_summary[
    duplicate_typecode_summary['plane_id'].isin(duplicate_plane_ids)
]

duplicate_typecode_summary.head(20)

duplicate plane_ids after normalization: 6

       plane_id unique_non_null_typecodes  typecode_count
124564   71010b                    [A342]               1
124640   7101e7                    [GLF4]               1
124641   7101e9                    [GLF4]               1
124644   7101f0                    [GLF4]               1
124664   71022b                    [B739]               1
124807   71032c                    [B752]               1

In [22]:
# Resolve only duplicated plane_ids — much faster than looping over all aircraft

duplicate_mask = df_ac_clean.duplicated(subset=['plane_id'], keep=False)

df_unique = df_ac_clean[~duplicate_mask].copy()
df_duplicates = df_ac_clean[duplicate_mask].copy()

# Normal rows
df_unique['typecode_status'] = np.where(
    df_unique['typecode'].notna(),
    'matched',
    'missing'
)
df_unique['source_rows'] = 1
df_unique['typecode_candidates'] = df_unique['typecode']


# Resolve only the duplicated plane_ids
resolved_duplicates = []

for plane_id, group in df_duplicates.groupby('plane_id'):

    valid_typecodes = sorted(set(group['typecode'].dropna()))

    # Keep the row with the most available metadata
    result = group.loc[group.notna().sum(axis=1).idxmax()].copy()

    if len(valid_typecodes) == 0:
        result['typecode'] = pd.NA
        result['typecode_status'] = 'missing'

    elif len(valid_typecodes) == 1:
        result['typecode'] = valid_typecodes[0]
        result['typecode_status'] = 'matched'

    else:
        result['typecode'] = pd.NA
        result['typecode_status'] = 'conflict'

    result['source_rows'] = len(group)
    result['typecode_candidates'] = (
        '|'.join(valid_typecodes) if valid_typecodes else pd.NA
    )

    resolved_duplicates.append(result)


df_resolved_duplicates = pd.DataFrame(resolved_duplicates)

# Put unique + resolved duplicated aircraft back together
df_ac_clean = pd.concat(
    [df_unique, df_resolved_duplicates],
    ignore_index=True
)

print('final aircraft rows:', len(df_ac_clean))
print('unique plane_ids:', df_ac_clean['plane_id'].nunique())

print('\ntypecode status:')
print(df_ac_clean['typecode_status'].value_counts())

print('\nremaining duplicate plane_ids:',
      df_ac_clean.duplicated(subset=['plane_id']).sum())

final aircraft rows: 519991
unique plane_ids: 519991

typecode status:
typecode_status
matched    479945
missing     40046
Name: count, dtype: int64

remaining duplicate plane_ids: 0

In [23]:
# Show any real conflicts for review. They remain in the dataset, but typecode is not guessed.
conflicts = df_ac_clean[df_ac_clean['typecode_status'] == 'conflict'][
    ['plane_id', 'typecode', 'typecode_candidates', 'source_rows']
]
print('real typecode conflicts:', len(conflicts))
conflicts.head(20)

real typecode conflicts: 0

Empty DataFrame
Columns: [plane_id, typecode, typecode_candidates, source_rows]
Index: []

In [24]:
df_ac_clean.head()

,plane_id,registration,manufacturericao,manufacturername,model,typecode,serialnumber,icaoaircrafttype,operator,operatoricao,owner,registered,reguntil,built,engines,categoryDescription,typecode_status,source_rows,typecode_candidates
0,aa3487,N757F,RAYTHEON,Raytheon Aircraft Company,A36,BE36,E-3121,L1P,<NA>,<NA>,Vintage Aircraft Llc,NaT,2027-01-31,NaT,<NA>,<NA>,matched,1,BE36
1,a4fa61,N42MH,PIPER,Piper,PA-31-350,PA31,31-7852015,L2P,<NA>,<NA>,Tvpx Aircraft Solutions Inc Trustee,NaT,2029-08-31,1977-01-01,LYCOMING TI0-540 SER,<NA>,matched,1,PA31
2,a7a809,N5926K,ROCKWELL,<NA>,<NA>,AC90,<NA>,L2T,<NA>,<NA>,<NA>,NaT,NaT,NaT,<NA>,<NA>,matched,1,AC90
3,391927,F-GGJH,ROBIN,Robin,DR.400 160 Chevalier,DR40,1795,L1P,<NA>,<NA>,Private,NaT,NaT,NaT,<NA>,<NA>,matched,1,DR40
4,503c21,LY-KNA,<NA>,Impulse Aircraft,Impulse 100,ZZZZ,<NA>,<NA>,<NA>,<NA>,Private,NaT,NaT,NaT,<NA>,<NA>,matched,1,ZZZZ

In [25]:
# Final check for issues 8 and 9

print("Columns after cleaning:")
print(df_ac_clean.columns.tolist())

print("\nDate column types:")
for col in ['built', 'registered', 'reguntil']:
    print(col, ":", df_ac_clean[col].dtype)

Columns after cleaning:
['plane_id', 'registration', 'manufacturericao', 'manufacturername', 'model', 'typecode', 'serialnumber', 'icaoaircrafttype', 'operator', 'operatoricao', 'owner', 'registered', 'reguntil', 'built', 'engines', 'categoryDescription', 'typecode_status', 'source_rows', 'typecode_candidates']

Date column types:
built : datetime64[us]
registered : datetime64[us]
reguntil : datetime64[us]

In [26]:
aircraft_output = INTERIM_DIR / 'cleaned_aircraft.csv'
df_ac_clean.to_csv(aircraft_output, index=False)
print('saved:', aircraft_output.resolve())

saved: /Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/data/interim/cleaned_aircraft.csv

## 9. Summary

In [27]:
summary = pd.DataFrame([
    {
        'dataset': 'OpenSky states',
        'raw_rows': len(df_sky),
        'cleaned_rows': len(df_sky_clean),
        'output': 'data/interim/cleaned_opensky.csv'
    },
    {
        'dataset': 'Open-Meteo hourly by location',
        'raw_rows': len(df_wx),
        'cleaned_rows': len(df_wx_clean),
        'output': 'data/interim/cleaned_weather.csv'
    },
    {
        'dataset': 'Aircraft type lookup',
        'raw_rows': len(df_ac),
        'cleaned_rows': len(df_ac_clean),
        'output': 'data/interim/cleaned_aircraft.csv'
    }
])

summary

,dataset,raw_rows,cleaned_rows,output
0,OpenSky states,485,485,data/interim/cleaned_opensky.csv
1,Open-Meteo hourly by location,10248,10248,data/interim/cleaned_weather.csv
2,Aircraft type lookup,520000,519991,data/interim/cleaned_aircraft.csv

In [28]:
print(df_ac_clean.columns.tolist())

['plane_id', 'registration', 'manufacturericao', 'manufacturername', 'model', 'typecode', 'serialnumber', 'icaoaircrafttype', 'operator', 'operatoricao', 'owner', 'registered', 'reguntil', 'built', 'engines', 'categoryDescription', 'typecode_status', 'source_rows', 'typecode_candidates']

In [29]:

print("=== FINAL CLEANING CHECK ===")
print("----------------------------")

# OpenSky
print("OpenSky rows:", len(df_sky_clean))
print(
    "OpenSky duplicate keys:",
    df_sky_clean.duplicated(
        ['plane_id', 'time_position']
    ).sum()
)

# Weather
print("\nWeather rows:", len(df_wx_clean))
print(
    "Weather location IDs:",
    df_wx_clean['location_id'].nunique()
)
print(
    "Weather duplicate keys:",
    df_wx_clean.duplicated(
        ['location_id', 'observation_time']
    ).sum()
)

# Aircraft
print("\nAircraft rows:", len(df_ac_clean))
print(
    "Aircraft duplicate IDs:",
    df_ac_clean['plane_id'].duplicated().sum()
)
print(
    "Aircraft typecode conflicts:",
    (df_ac_clean['typecode_status'] == 'conflict').sum()
)

print("\nTypecode status:")
print(
    df_ac_clean['typecode_status']
    .value_counts(dropna=False)
)

=== FINAL CLEANING CHECK ===
----------------------------
OpenSky rows: 485
OpenSky duplicate keys: 26

Weather rows: 10248
Weather location IDs: 150
Weather duplicate keys: 4392

Aircraft rows: 519991
Aircraft duplicate IDs: 0
Aircraft typecode conflicts: 0

Typecode status:
typecode_status
matched    479945
missing     40046
Name: count, dtype: int64