# Task 4 — Join, Transformation Rules, and Testing

## SkyPrint

### Objective

Build a transformation pipeline that integrates validated flight, aircraft, and weather data for flights over Saudi Arabia.

The final dataset will support two main analytical goals:

1. **Air Traffic Analysis**
   - Preserve flight position and time information for traffic-density analysis.
   - Support future route-overload analysis when repeated OpenSky snapshots are collected.

2. **Environmental Analysis**
   - Enrich flight observations with aircraft metadata and weather conditions.
   - Prepare valid observations for fuel-consumption and emissions estimation using OpenAP.

### Design Principles

- Use validated outputs from Task 3.
- Keep the transformation compatible with future repeated snapshots.
- Document and test every join and transformation rule.
- Do not silently drop unmatched records.
- Check row counts and duplicate keys after joins.
- Produce the final analysis-ready dataset as `data/processed/final.csv`.

> Note: The current OpenSky data is a single snapshot. Therefore, the pipeline can prepare traffic features, but reliable route-overload analysis requires repeated snapshots over time.

## 1. Join Specification

Task 4 uses the validated outputs produced by Task 3.

### Input Datasets

| Dataset | Purpose | Key / Matching Method |
|---|---|---|
| Validated OpenSky | Base flight observations | `plane_id` |
| Validated Aircraft | Aircraft metadata and OpenAP type information | `plane_id` |
| Validated Weather | Atmospheric conditions | Spatial + temporal + altitude matching |

### Join 1 — OpenSky + Aircraft

- **Base dataset:** OpenSky
- **Join key:** `plane_id`
- **Join type:** Left join
- **Relationship:** Many-to-one
- **Reason:** Preserve every valid flight observation even when aircraft metadata is unavailable.
- **Duplicate handling:** Aircraft `plane_id` must be unique before the join. Duplicate keys are treated as an error rather than silently removed.

### Join 2 — Flight + Weather

Weather cannot be joined using `plane_id`.

Each flight observation will be matched to weather using:
- geographic location,
- observation time,
- and the atmospheric level appropriate to the aircraft altitude.

The matching logic will be implemented and tested explicitly before weather attributes are added.

### Row-count Policy

- Row counts will be measured before and after every join.
- Enrichment joins must not unexpectedly multiply flight observations.
- Unmatched records will be retained and flagged rather than silently dropped.

In [12]:
from pathlib import Path
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 100)

# Project paths
CWD = Path.cwd()
PROJECT_ROOT = CWD.parent if CWD.name == "notebooks" else CWD

INTERIM_DIR = PROJECT_ROOT / "data" / "interim"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Interim folder:", INTERIM_DIR)
print("Processed folder:", PROCESSED_DIR)

Project root: /Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint
Interim folder: /Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/data/interim
Processed folder: /Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/data/processed

In [13]:
# Check Task 3 outputs available for Task 4

task3_files = sorted(INTERIM_DIR.glob("*.csv"))

print("Task 3 / interim files:")
for file in task3_files:
    print("-", file.name)

Task 3 / interim files:
- cleaned_aircraft.csv
- cleaned_opensky.csv
- cleaned_weather.csv
- rejected.csv
- rejected_aircraft.csv
- rejected_opensky.csv
- rejected_weather.csv
- schema_aircraft.csv
- schema_opensky.csv
- schema_weather.csv
- skyprint_readiness.csv
- validated.csv
- validated_aircraft.csv
- validated_opensky.csv
- validated_weather.csv
- validation_summary.csv

In [14]:
# Load validated Task 3 outputs

sky = pd.read_csv(INTERIM_DIR / "validated_opensky.csv")
aircraft = pd.read_csv(INTERIM_DIR / "validated_aircraft.csv")
weather = pd.read_csv(INTERIM_DIR / "validated_weather.csv")

print("Validated OpenSky:", sky.shape)
print("Validated Aircraft:", aircraft.shape)
print("Validated Weather:", weather.shape)

Validated OpenSky: (433, 24)
Validated Aircraft: (519969, 27)
Validated Weather: (3600, 36)

In [15]:
# Inspect columns and join keys before transformation

print("=== OPENSKY COLUMNS ===")
print(sky.columns.tolist())

print("\n=== AIRCRAFT COLUMNS ===")
print(aircraft.columns.tolist())

print("\n=== WEATHER COLUMNS ===")
print(weather.columns.tolist())

print("\n=== KEY CHECKS ===")
print("OpenSky rows:", len(sky))
print("OpenSky plane_id nulls:", sky["plane_id"].isna().sum())

print("Aircraft rows:", len(aircraft))
print("Aircraft plane_id nulls:", aircraft["plane_id"].isna().sum())
print("Aircraft plane_id duplicates:", aircraft["plane_id"].duplicated().sum())

print("Weather rows:", len(weather))
print("Weather location_id nulls:", weather["location_id"].isna().sum())

=== OPENSKY COLUMNS ===
['plane_id', 'flight_id', 'origin_country', 'time_position', 'last_contact', 'longitude', 'latitude', 'baro_altitude', 'on_ground', 'velocity', 'true_track', 'vertical_rate', 'geo_altitude', 'source_type', 'category', 'batch_id', 'source_file', 'rejection_reason', 'schema_valid', 'position_ready', 'trajectory_point_ready', 'kinematic_inputs_present', 'inside_extraction_bbox', 'inside_saudi_boundary']

=== AIRCRAFT COLUMNS ===
['plane_id', 'registration', 'manufacturericao', 'manufacturername', 'model', 'typecode', 'serialnumber', 'icaoaircrafttype', 'operator', 'operatoricao', 'owner', 'registered', 'reguntil', 'built', 'engines', 'categoryDescription', 'typecode_status', 'source_rows', 'typecode_candidates', 'rejection_reason', 'schema_valid', 'openap_typecode', 'openap_resolution', 'openap_supported', 'openap_resolution_note', 'metadata_ready', 'fuel_model_ready']

=== WEATHER COLUMNS ===
['observation_time', 'temperature_850hPa', 'wind_speed_850hPa', 'wind_direction_850hPa', 'geopotential_height_850hPa', 'temperature_700hPa', 'wind_speed_700hPa', 'wind_direction_700hPa', 'geopotential_height_700hPa', 'temperature_500hPa', 'wind_speed_500hPa', 'wind_direction_500hPa', 'geopotential_height_500hPa', 'temperature_300hPa', 'wind_speed_300hPa', 'wind_direction_300hPa', 'geopotential_height_300hPa', 'temperature_250hPa', 'wind_speed_250hPa', 'wind_direction_250hPa', 'geopotential_height_250hPa', 'temperature_200hPa', 'wind_speed_200hPa', 'wind_direction_200hPa', 'geopotential_height_200hPa', 'latitude', 'longitude', 'elevation_m', 'location_id', 'timezone', 'batch_id', 'source_file', 'rejection_reason', 'schema_valid', 'pressure_weather_available', 'weather_ready']

=== KEY CHECKS ===
OpenSky rows: 433
OpenSky plane_id nulls: 0
Aircraft rows: 519969
Aircraft plane_id nulls: 0
Aircraft plane_id duplicates: 0
Weather rows: 3600
Weather location_id nulls: 0

## 2. Join Flight and Aircraft Data

Join validated OpenSky flight observations with validated aircraft metadata using `plane_id`.

A left join is used to preserve all flight observations, including aircraft without matching metadata. The aircraft key must remain unique to prevent row multiplication.

In [16]:
# Join OpenSky flight observations with aircraft metadata

aircraft_cols = [
    "plane_id",
    "registration",
    "manufacturername",
    "model",
    "typecode",
    "engines",
    "categoryDescription",
    "openap_typecode",
    "openap_resolution",
    "openap_supported",
    "metadata_ready",
    "fuel_model_ready"
]

flight_aircraft = sky.merge(
    aircraft[aircraft_cols],
    on="plane_id",
    how="left",
    validate="many_to_one"
)

# Flag successful aircraft metadata matches
flight_aircraft["aircraft_metadata_matched"] = (
    flight_aircraft["metadata_ready"].fillna(False).astype(bool)
)

print("Rows before join:", len(sky))
print("Rows after join:", len(flight_aircraft))
print(
    "Aircraft metadata matched:",
    int(flight_aircraft["aircraft_metadata_matched"].sum())
)
print(
    "OpenAP ready:",
    int(flight_aircraft["openap_supported"].fillna(False).sum())
)

Rows before join: 433
Rows after join: 433
Aircraft metadata matched: 299
OpenAP ready: 256

In [17]:
# Test Join 1

assert len(flight_aircraft) == len(sky), \
    "Join 1 failed: row count changed."

assert flight_aircraft["plane_id"].isna().sum() == 0, \
    "Join 1 failed: null plane_id found."

assert aircraft["plane_id"].duplicated().sum() == 0, \
    "Join 1 failed: duplicate aircraft keys found."

print("JOIN 1 TEST: PASS")
print("All OpenSky observations were preserved without row multiplication.")

JOIN 1 TEST: PASS
All OpenSky observations were preserved without row multiplication.

## 3. Match Flight and Weather Data

Match each flight observation with the most appropriate weather observation using location and time.

Because weather conditions are provided at multiple atmospheric pressure levels, the aircraft altitude will then be used to select the weather level that best represents the aircraft's flight conditions.

The matching process must preserve all flight observations and avoid row multiplication.

In [18]:
# Inspect flight and weather matching fields

print("=== FLIGHT SAMPLE ===")
display(
    flight_aircraft[
        ["plane_id", "time_position", "latitude", "longitude",
         "baro_altitude", "geo_altitude"]
    ].head()
)

print("\n=== WEATHER SAMPLE ===")
display(
    weather[
        ["location_id", "observation_time", "latitude", "longitude"]
    ].head()
)

print("\nFlight time range:")
print(flight_aircraft["time_position"].min(), "->",
      flight_aircraft["time_position"].max())

print("\nWeather time range:")
print(weather["observation_time"].min(), "->",
      weather["observation_time"].max())

print("\nUnique weather locations:",
      weather["location_id"].nunique())

=== FLIGHT SAMPLE ===

,plane_id,time_position,latitude,longitude,baro_altitude,geo_altitude
0,801619,2026-09-21 20:47:46+00:00,25.2288,55.8897,1493.52,1562.10
1,801673,2026-09-21 20:47:46+00:00,25.1996,55.1700,1813.56,1874.52
2,80169c,2026-09-21 20:45:33+00:00,21.8863,54.0266,11887.20,12641.58
3,778823,2026-09-21 20:47:24+00:00,27.4207,48.5936,10355.58,11064.24
4,8015e5,2026-09-21 20:47:45+00:00,24.4297,54.9076,3893.82,4130.04

=== WEATHER SAMPLE ===

   location_id           observation_time  latitude  longitude
0            0  2026-09-20 00:00:00+00:00  24.49912  54.423077
1            0  2026-09-20 01:00:00+00:00  24.49912  54.423077
2            0  2026-09-20 02:00:00+00:00  24.49912  54.423077
3            0  2026-09-20 03:00:00+00:00  24.49912  54.423077
4            0  2026-09-20 04:00:00+00:00  24.49912  54.423077

Flight time range:
2026-09-20 05:01:48+00:00 -> 2026-09-21 20:50:04+00:00

Weather time range:
2026-09-20 00:00:00+00:00 -> 2026-09-20 23:00:00+00:00

Unique weather locations: 150

In [19]:
# Prepare timestamps for weather matching

flight_aircraft["time_position"] = pd.to_datetime(
    flight_aircraft["time_position"],
    utc=True
)

weather["observation_time"] = pd.to_datetime(
    weather["observation_time"],
    utc=True
)

# Match each flight observation to the nearest weather hour
flight_aircraft["weather_time"] = (
    flight_aircraft["time_position"].dt.round("h")
)

print(
    flight_aircraft[
        ["plane_id", "time_position", "weather_time"]
    ].head()
)

print(
    "\nWeather times available:",
    weather["observation_time"].nunique()
)

  plane_id             time_position              weather_time
0   801619 2026-09-21 20:47:46+00:00 2026-09-21 21:00:00+00:00
1   801673 2026-09-21 20:47:46+00:00 2026-09-21 21:00:00+00:00
2   80169c 2026-09-21 20:45:33+00:00 2026-09-21 21:00:00+00:00
3   778823 2026-09-21 20:47:24+00:00 2026-09-21 21:00:00+00:00
4   8015e5 2026-09-21 20:47:45+00:00 2026-09-21 21:00:00+00:00

Weather times available: 24

In [20]:
# Find the nearest weather location for each flight observation.
# IMPORTANT: candidates are restricted to the same extraction batch.
weather_locations = (
    weather[["batch_id", "location_id", "latitude", "longitude"]]
    .drop_duplicates(["batch_id", "location_id"])
    .reset_index(drop=True)
)

def find_nearest_weather_location(row):
    candidates = weather_locations[
        weather_locations["batch_id"] == row["batch_id"]
    ]
    if candidates.empty or pd.isna(row["latitude"]) or pd.isna(row["longitude"]):
        return pd.NA
    distances = (
        (candidates["latitude"] - row["latitude"]) ** 2
        + (candidates["longitude"] - row["longitude"]) ** 2
    )
    nearest_index = distances.idxmin()
    return candidates.loc[nearest_index, "location_id"]

flight_aircraft["weather_location_id"] = flight_aircraft.apply(
    find_nearest_weather_location, axis=1
)

print(flight_aircraft[["batch_id", "plane_id", "latitude", "longitude", "weather_location_id"]].head())
print("Flights with weather location:", flight_aircraft["weather_location_id"].notna().sum(), "/", len(flight_aircraft))

          batch_id plane_id  latitude  longitude weather_location_id
0  20260921_234752   801619   25.2288    55.8897                <NA>
1  20260921_234752   801673   25.1996    55.1700                <NA>
2  20260921_234752   80169c   21.8863    54.0266                <NA>
3  20260921_234752   778823   27.4207    48.5936                <NA>
4  20260921_234752   8015e5   24.4297    54.9076                <NA>
Flights with weather location: 163 / 433

In [21]:
# Calculate distance to the matched weather location

weather_location_lookup = weather_locations.rename(
    columns={
        "latitude": "weather_latitude",
        "longitude": "weather_longitude"
    }
)

flight_aircraft = flight_aircraft.merge(
    weather_location_lookup,
    left_on=["batch_id", "weather_location_id"],
    right_on=["batch_id", "location_id"],
    how="left",
    validate="many_to_one"
)

# Haversine distance in kilometers
lat1 = np.radians(flight_aircraft["latitude"])
lon1 = np.radians(flight_aircraft["longitude"])
lat2 = np.radians(flight_aircraft["weather_latitude"])
lon2 = np.radians(flight_aircraft["weather_longitude"])

dlat = lat2 - lat1
dlon = lon2 - lon1

a = (
    np.sin(dlat / 2) ** 2
    + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
)

flight_aircraft["weather_distance_km"] = (
    6371 * 2 * np.arcsin(np.sqrt(a))
)

print(
    flight_aircraft[
        [
            "plane_id",
            "latitude",
            "longitude",
            "weather_latitude",
            "weather_longitude",
            "weather_distance_km"
        ]
    ].head()
)

print("\nMaximum distance (km):",
      round(flight_aircraft["weather_distance_km"].max(), 2))

print("Average distance (km):",
      round(flight_aircraft["weather_distance_km"].mean(), 2))

  plane_id  latitude  longitude  weather_latitude  weather_longitude  \
0   801619   25.2288    55.8897               NaN                NaN
1   801673   25.1996    55.1700               NaN                NaN
2   80169c   21.8863    54.0266               NaN                NaN
3   778823   27.4207    48.5936               NaN                NaN
4   8015e5   24.4297    54.9076               NaN                NaN

   weather_distance_km
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN

Maximum distance (km): 21.42
Average distance (km): 5.09

In [22]:
# Keep only complete batches

common_batches = (
    set(flight_aircraft["batch_id"].dropna().astype(str))
    & set(weather["batch_id"].dropna().astype(str))
)

flight_aircraft = flight_aircraft[
    flight_aircraft["batch_id"].astype(str).isin(common_batches)
].copy()

weather = weather[
    weather["batch_id"].astype(str).isin(common_batches)
].copy()

print("Complete batches:", sorted(common_batches))
print("Flight rows:", len(flight_aircraft))
print("Weather rows:", len(weather))

Complete batches: ['20260920_054121']
Flight rows: 163
Weather rows: 3600

In [23]:
# Join flight observations with weather by location and time

flight_weather = flight_aircraft.merge(
    weather,
    left_on=["batch_id", "weather_location_id", "weather_time"],
    right_on=["batch_id", "location_id", "observation_time"],
    how="left",
    validate="many_to_one",
    suffixes=("", "_weather")
)

print("Rows before weather join:", len(flight_aircraft))
print("Rows after weather join:", len(flight_weather))

print(
    "Weather matched:",
    int(flight_weather["weather_ready"].fillna(False).sum()),
    "/",
    len(flight_weather)
)

Rows before weather join: 163
Rows after weather join: 163
Weather matched: 163 / 163

In [24]:
# Test weather join

assert len(flight_weather) == len(flight_aircraft), \
    "Weather join failed: row count changed."

assert flight_weather["observation_time"].notna().all(), \
    "Weather join failed: some flights have no weather observation."

assert flight_weather["weather_ready"].fillna(False).all(), \
    "Weather join failed: some matched weather records are not ready."

assert (
    flight_weather["weather_location_id"]
    == flight_weather["location_id"]
).all(), "Weather join failed: location mismatch."

assert (
    flight_weather["weather_time"]
    == flight_weather["observation_time"]
).all(), "Weather join failed: time mismatch."

print("WEATHER JOIN TEST: PASS")
print("All flight observations have one valid weather match.")

WEATHER JOIN TEST: PASS
All flight observations have one valid weather match.

In [25]:
# Select the atmospheric pressure level nearest to each airborne flight altitude

pressure_levels = [850, 700, 500, 300, 250, 200]

# Prefer geometric altitude, fall back to barometric altitude
flight_weather["flight_altitude_m"] = (
    flight_weather["geo_altitude"]
    .fillna(flight_weather["baro_altitude"])
)

height_difference = pd.DataFrame(
    {
        level: abs(
            flight_weather[f"geopotential_height_{level}hPa"].to_numpy()
            - flight_weather["flight_altitude_m"].to_numpy()
        )
        for level in pressure_levels
    },
    index=flight_weather.index
)

# Keep pressure level missing when altitude is unavailable
valid_altitude = flight_weather["flight_altitude_m"].notna()

flight_weather["pressure_level_hpa"] = pd.NA

flight_weather.loc[valid_altitude, "pressure_level_hpa"] = (
    height_difference.loc[valid_altitude].idxmin(axis=1)
)

flight_weather["pressure_level_hpa"] = (
    flight_weather["pressure_level_hpa"].astype("Int64")
)

print("Total flight observations:", len(flight_weather))
print("Altitude available:", int(valid_altitude.sum()))
print("Altitude unavailable:", int((~valid_altitude).sum()))

print("\nSelected pressure levels:")
print(
    flight_weather["pressure_level_hpa"]
    .value_counts(dropna=False)
    .sort_index()
)

Total flight observations: 163
Altitude available: 158
Altitude unavailable: 5

Selected pressure levels:
pressure_level_hpa
200     14
250     44
300     26
500     23
700     21
850     30
<NA>     5
Name: count, dtype: Int64

In [26]:
# Verify pressure-level selection against aircraft altitude

pressure_check = (
    flight_weather
    .dropna(subset=["pressure_level_hpa"])
    .groupby("pressure_level_hpa")["flight_altitude_m"]
    .agg(["count", "min", "mean", "max"])
    .round(1)
)

print("=== PRESSURE LEVEL vs FLIGHT ALTITUDE ===")
display(pressure_check)

assert pressure_check.index.isin([850, 700, 500, 300, 250, 200]).all()
assert pressure_check["count"].sum() == flight_weather["pressure_level_hpa"].notna().sum()

print("\nPRESSURE LEVEL CHECK: PASS")

=== PRESSURE LEVEL vs FLIGHT ALTITUDE ===

                    count      min     mean      max
pressure_level_hpa
200                    14  11887.2  12359.1  12672.1
250                    44  10309.9  11122.8  11711.9
300                    26   7818.1   9221.7  10416.5
500                    23   4602.5   6254.4   7825.7
700                    21   2545.1   3468.6   4564.4
850                    30    -15.2    910.1   2270.8

PRESSURE LEVEL CHECK: PASS

## 4. Select Altitude-Matched Weather Conditions

For each flight observation with a valid altitude, select temperature, wind speed, and wind direction from the atmospheric pressure level matched to the aircraft altitude.

Flights without a valid altitude are retained, but altitude-dependent weather attributes remain unavailable.

These derived weather attributes will later support wind-aware flight features and fuel/emissions estimation.

In [27]:
# Select weather variables from the pressure level matched to each flight altitude

flight_weather["flight_temperature_c"] = np.nan
flight_weather["flight_wind_speed_kmh"] = np.nan
flight_weather["flight_wind_direction_deg"] = np.nan

for level in pressure_levels:
    mask = flight_weather["pressure_level_hpa"].eq(level)

    flight_weather.loc[mask, "flight_temperature_c"] = (
        flight_weather.loc[mask, f"temperature_{level}hPa"]
    )

    flight_weather.loc[mask, "flight_wind_speed_kmh"] = (
        flight_weather.loc[mask, f"wind_speed_{level}hPa"]
    )

    flight_weather.loc[mask, "flight_wind_direction_deg"] = (
        flight_weather.loc[mask, f"wind_direction_{level}hPa"]
    )

print("=== ALTITUDE-MATCHED WEATHER ===")

display(
    flight_weather[
        [
            "plane_id",
            "flight_altitude_m",
            "pressure_level_hpa",
            "flight_temperature_c",
            "flight_wind_speed_kmh",
            "flight_wind_direction_deg"
        ]
    ].head(10)
)

print("\nWeather attributes available:")
print("Temperature:", flight_weather["flight_temperature_c"].notna().sum())
print("Wind speed:", flight_weather["flight_wind_speed_kmh"].notna().sum())
print("Wind direction:", flight_weather["flight_wind_direction_deg"].notna().sum())

=== ALTITUDE-MATCHED WEATHER ===

,plane_id,flight_altitude_m,pressure_level_hpa,flight_temperature_c,flight_wind_speed_kmh,flight_wind_direction_deg
0,778823,1508.76,850,28.5,22.6,261.0
1,710435,11399.52,250,-41.5,9.4,130.0
2,728675,11361.42,250,-42.0,31.4,227.0
3,70203f,11384.28,250,-40.5,24.7,51.0
4,801883,8808.72,300,-30.5,18.3,238.0
5,4bb46f,NaN,<NA>,NaN,NaN,NaN
6,738056,NaN,<NA>,NaN,NaN,NaN
7,89611b,7025.64,500,-4.2,35.7,20.0
8,89611f,9768.84,300,-31.0,20.4,230.0
9,89611e,1965.96,850,28.5,22.9,264.0

Weather attributes available:
Temperature: 158
Wind speed: 158
Wind direction: 158

In [28]:
# Test altitude-matched weather attributes

valid_weather = flight_weather["pressure_level_hpa"].notna()

assert flight_weather.loc[
    valid_weather, "flight_temperature_c"
].notna().all(), "Missing matched temperature."

assert flight_weather.loc[
    valid_weather, "flight_wind_speed_kmh"
].notna().all(), "Missing matched wind speed."

assert flight_weather.loc[
    valid_weather, "flight_wind_direction_deg"
].notna().all(), "Missing matched wind direction."

assert (
    flight_weather.loc[valid_weather, "flight_wind_speed_kmh"] >= 0
).all(), "Negative wind speed found."

assert flight_weather.loc[
    valid_weather, "flight_wind_direction_deg"
].between(0, 360).all(), "Invalid wind direction found."

print("ALTITUDE-MATCHED WEATHER TEST: PASS")
print("Valid altitude/weather observations:", int(valid_weather.sum()))
print("Rows retained without altitude:", int((~valid_weather).sum()))

ALTITUDE-MATCHED WEATHER TEST: PASS
Valid altitude/weather observations: 158
Rows retained without altitude: 5

## 5. Derive Wind Components and Airspeed Inputs

Use the altitude-matched wind conditions together with aircraft ground speed and true track to derive wind-aware flight features.

OpenSky `velocity` represents ground speed, so it will not be treated directly as true airspeed. Wind speed and direction will be used to derive the aircraft airspeed inputs required for later fuel-flow and emissions estimation.

Rows with insufficient kinematic or weather data will be retained and flagged rather than assigned artificial values.

In [29]:
# Check inputs required for wind-aware airspeed calculation

airspeed_input_cols = [
    "velocity",
    "true_track",
    "flight_wind_speed_kmh",
    "flight_wind_direction_deg"
]

print("=== AIRSPEED INPUT CHECK ===")

for col in airspeed_input_cols:
    print(
        f"{col}:",
        "available =", flight_weather[col].notna().sum(),
        "| missing =", flight_weather[col].isna().sum()
    )

airspeed_inputs_ready = flight_weather[airspeed_input_cols].notna().all(axis=1)

print("\nTotal observations:", len(flight_weather))
print("Airspeed inputs ready:", int(airspeed_inputs_ready.sum()))
print("Airspeed inputs unavailable:", int((~airspeed_inputs_ready).sum()))

print("\nRows with unavailable inputs:")
display(
    flight_weather.loc[
        ~airspeed_inputs_ready,
        ["plane_id", "flight_id"] + airspeed_input_cols
    ]
)

=== AIRSPEED INPUT CHECK ===
velocity: available = 163 | missing = 0
true_track: available = 163 | missing = 0
flight_wind_speed_kmh: available = 158 | missing = 5
flight_wind_direction_deg: available = 158 | missing = 5

Total observations: 163
Airspeed inputs ready: 158
Airspeed inputs unavailable: 5

Rows with unavailable inputs:

,plane_id,flight_id,velocity,true_track,flight_wind_speed_kmh,flight_wind_direction_deg
5,4bb46f,MNB6500,8.23,300.94,NaN,NaN
6,738056,NaN,10.80,30.94,NaN,NaN
18,500194,ELY882,6.43,112.50,NaN,NaN
30,4c80b4,BBG691,2.31,300.94,NaN,NaN
150,06a149,NaN,4.63,236.25,NaN,NaN

In [30]:
# Convert wind speed from km/h to m/s
flight_weather["flight_wind_speed_ms"] = (
    flight_weather["flight_wind_speed_kmh"] / 3.6
)

# Relative angle between the direction the wind comes FROM
# and the aircraft ground track
relative_wind_angle_rad = np.deg2rad(
    flight_weather["flight_wind_direction_deg"]
    - flight_weather["true_track"]
)

# Wind component along the aircraft track
# Positive = headwind, Negative = tailwind
flight_weather["headwind_component_ms"] = (
    flight_weather["flight_wind_speed_ms"]
    * np.cos(relative_wind_angle_rad)
)

# Crosswind magnitude
flight_weather["crosswind_component_ms"] = (
    flight_weather["flight_wind_speed_ms"]
    * np.sin(relative_wind_angle_rad)
)

print("=== WIND COMPONENTS SAMPLE ===")

display(
    flight_weather[
        [
            "plane_id",
            "velocity",
            "true_track",
            "flight_wind_speed_ms",
            "flight_wind_direction_deg",
            "headwind_component_ms",
            "crosswind_component_ms"
        ]
    ].head(10)
)

=== WIND COMPONENTS SAMPLE ===

,plane_id,velocity,true_track,flight_wind_speed_ms,flight_wind_direction_deg,headwind_component_ms,crosswind_component_ms
0,778823,121.54,92.67,6.277778,261.0,-6.148009,1.269835
1,710435,235.70,103.76,2.611111,130.0,2.342036,1.154456
2,728675,242.23,113.13,8.722222,227.0,-3.529559,7.976175
3,70203f,247.33,67.76,6.861111,51.0,6.569658,-1.978493
4,801883,232.45,104.22,5.083333,238.0,-3.517114,3.670176
5,4bb46f,8.23,300.94,NaN,NaN,NaN,NaN
6,738056,10.80,30.94,NaN,NaN,NaN,NaN
7,89611b,237.86,210.84,9.916667,20.0,-9.739716,1.864998
8,89611f,248.78,298.00,5.666667,230.0,2.122771,-5.254042
9,89611e,138.74,234.66,6.361111,264.0,5.545155,3.116888

In [31]:
# Test derived wind components

valid_wind = airspeed_inputs_ready

assert flight_weather.loc[
    valid_wind, "flight_wind_speed_ms"
].ge(0).all(), "Negative wind speed found."

assert (
    flight_weather.loc[valid_wind, "headwind_component_ms"].abs()
    <= flight_weather.loc[valid_wind, "flight_wind_speed_ms"] + 1e-9
).all(), "Headwind component exceeds total wind speed."

assert (
    flight_weather.loc[valid_wind, "crosswind_component_ms"].abs()
    <= flight_weather.loc[valid_wind, "flight_wind_speed_ms"] + 1e-9
).all(), "Crosswind component exceeds total wind speed."

assert flight_weather.loc[
    valid_wind,
    ["headwind_component_ms", "crosswind_component_ms"]
].notna().all().all(), "Missing wind components found."

print("WIND COMPONENT TEST: PASS")
print("Valid wind-component observations:", int(valid_wind.sum()))
print("Rows retained without wind components:", int((~valid_wind).sum()))

WIND COMPONENT TEST: PASS
Valid wind-component observations: 158
Rows retained without wind components: 5

In [32]:
# Derive airspeed from ground-speed and wind vectors

track_rad = np.deg2rad(flight_weather["true_track"])
wind_from_rad = np.deg2rad(flight_weather["flight_wind_direction_deg"])

# Ground-velocity vector: east and north components
ground_east_ms = flight_weather["velocity"] * np.sin(track_rad)
ground_north_ms = flight_weather["velocity"] * np.cos(track_rad)

# Meteorological wind direction tells where wind comes FROM.
# Convert it to the direction the wind moves TOWARD.
wind_east_ms = -flight_weather["flight_wind_speed_ms"] * np.sin(wind_from_rad)
wind_north_ms = -flight_weather["flight_wind_speed_ms"] * np.cos(wind_from_rad)

# Air velocity = ground velocity - wind velocity
air_east_ms = ground_east_ms - wind_east_ms
air_north_ms = ground_north_ms - wind_north_ms

flight_weather["derived_airspeed_ms"] = np.sqrt(
    air_east_ms**2 + air_north_ms**2
)

# Keep airspeed unavailable when required inputs are unavailable
flight_weather.loc[
    ~airspeed_inputs_ready, "derived_airspeed_ms"
] = np.nan

print("=== DERIVED AIRSPEED SAMPLE ===")

display(
    flight_weather[
        [
            "plane_id",
            "velocity",
            "flight_wind_speed_ms",
            "headwind_component_ms",
            "crosswind_component_ms",
            "derived_airspeed_ms"
        ]
    ].head(10)
)

print(
    "\nDerived airspeed available:",
    flight_weather["derived_airspeed_ms"].notna().sum(),
    "/",
    len(flight_weather)
)

=== DERIVED AIRSPEED SAMPLE ===

,plane_id,velocity,flight_wind_speed_ms,headwind_component_ms,crosswind_component_ms,derived_airspeed_ms
0,778823,121.54,6.277778,-6.148009,1.269835,115.398978
1,710435,235.70,2.611111,2.342036,1.154456,238.044835
2,728675,242.23,8.722222,-3.529559,7.976175,238.833666
3,70203f,247.33,6.861111,6.569658,-1.978493,253.907367
4,801883,232.45,5.083333,-3.517114,3.670176,228.962304
5,4bb46f,8.23,NaN,NaN,NaN,NaN
6,738056,10.80,NaN,NaN,NaN,NaN
7,89611b,237.86,9.916667,-9.739716,1.864998,228.127908
8,89611f,248.78,5.666667,2.122771,-5.254042,250.957776
9,89611e,138.74,6.361111,5.545155,3.116888,144.318817

Derived airspeed available: 158 / 163

In [33]:
# Test derived airspeed

valid_airspeed = airspeed_inputs_ready

assert flight_weather.loc[
    valid_airspeed, "derived_airspeed_ms"
].notna().all(), "Missing derived airspeed for valid inputs."

assert (
    flight_weather.loc[valid_airspeed, "derived_airspeed_ms"] > 0
).all(), "Non-positive derived airspeed found."

assert flight_weather.loc[
    ~valid_airspeed, "derived_airspeed_ms"
].isna().all(), "Airspeed was created for rows with insufficient inputs."

print("DERIVED AIRSPEED TEST: PASS")
print("Derived airspeed observations:", int(valid_airspeed.sum()))
print("Rows retained without derived airspeed:", int((~valid_airspeed).sum()))

print(
    "Derived airspeed range (m/s):",
    round(flight_weather.loc[valid_airspeed, "derived_airspeed_ms"].min(), 2),
    "->",
    round(flight_weather.loc[valid_airspeed, "derived_airspeed_ms"].max(), 2)
)

DERIVED AIRSPEED TEST: PASS
Derived airspeed observations: 158
Rows retained without derived airspeed: 5
Derived airspeed range (m/s): 5.38 -> 263.12

## 6. Prepare OpenAP Fuel-Flow Inputs

Prepare the validated flight observations for fuel-flow estimation using OpenAP.

Only observations with supported aircraft types and the required flight-state inputs will be eligible for fuel-flow estimation. Rows that are not eligible will be retained and explicitly flagged rather than assigned estimated values.

In [34]:
# Check readiness for OpenAP fuel-flow estimation

fuel_input_cols = [
    "openap_typecode",
    "derived_airspeed_ms",
    "flight_altitude_m",
    "vertical_rate"
]

print("=== OPENAP FUEL-FLOW INPUT CHECK ===")

for col in fuel_input_cols:
    print(
        f"{col}:",
        "available =", flight_weather[col].notna().sum(),
        "| missing =", flight_weather[col].isna().sum()
    )

fuel_ready = (
    flight_weather["fuel_model_ready"].fillna(False).astype(bool)
    & flight_weather["openap_typecode"].notna()
    & flight_weather["derived_airspeed_ms"].notna()
    & flight_weather["flight_altitude_m"].notna()
    & flight_weather["vertical_rate"].notna()
)

flight_weather["fuel_flow_ready"] = fuel_ready

print("\nTotal observations:", len(flight_weather))
print("Fuel-flow ready:", int(fuel_ready.sum()))
print("Not fuel-flow ready:", int((~fuel_ready).sum()))

display(
    flight_weather[
        [
            "plane_id",
            "flight_id",
            "openap_typecode",
            "fuel_model_ready",
            "derived_airspeed_ms",
            "flight_altitude_m",
            "vertical_rate",
            "fuel_flow_ready"
        ]
    ].head(10)
)

=== OPENAP FUEL-FLOW INPUT CHECK ===
openap_typecode: available = 92 | missing = 71
derived_airspeed_ms: available = 158 | missing = 5
flight_altitude_m: available = 158 | missing = 5
vertical_rate: available = 155 | missing = 8

Total observations: 163
Fuel-flow ready: 88
Not fuel-flow ready: 75

,plane_id,flight_id,openap_typecode,fuel_model_ready,derived_airspeed_ms,flight_altitude_m,vertical_rate,fuel_flow_ready
0,778823,FYC731,NaN,NaN,115.398978,1508.76,-2.93,False
1,710435,KNE201,A20N,True,238.044835,11399.52,-0.33,True
2,728675,IAW443,B738,True,238.833666,11361.42,0.00,True
3,70203f,BBC340,B77W,True,253.907367,11384.28,0.00,True
4,801883,IGO19M,NaN,NaN,228.962304,8808.72,6.83,False
5,4bb46f,MNB6500,NaN,NaN,NaN,NaN,NaN,False
6,738056,NaN,B739,True,NaN,NaN,NaN,False
7,89611b,UAE135,B77W,True,228.127908,7025.64,13.00,True
8,89611f,UAE58Q,B77W,True,250.957776,9768.84,0.00,True
9,89611e,UAE59,B77W,True,144.318817,1965.96,12.03,True

In [35]:
from openap import prop

# Convert flight-state data to OpenAP input units
flight_weather["tas_kts"] = flight_weather["derived_airspeed_ms"] * 1.943844
flight_weather["altitude_ft"] = flight_weather["flight_altitude_m"] * 3.28084
flight_weather["vertical_rate_fpm"] = flight_weather["vertical_rate"] * 196.850394

# Estimate aircraft mass as 85% of MTOW
flight_weather["estimated_mass_kg"] = np.nan

for idx in flight_weather.index[flight_weather["fuel_flow_ready"]]:
    typecode = flight_weather.at[idx, "openap_typecode"]
    aircraft = prop.aircraft(typecode, use_synonym=True)

    flight_weather.at[idx, "estimated_mass_kg"] = (
        aircraft["mtow"] * 0.85
    )

print("=== OPENAP INPUTS PREPARED ===")
print(
    "Mass estimates available:",
    flight_weather["estimated_mass_kg"].notna().sum()
)

display(
    flight_weather.loc[
        flight_weather["fuel_flow_ready"],
        [
            "plane_id",
            "openap_typecode",
            "estimated_mass_kg",
            "tas_kts",
            "altitude_ft",
            "vertical_rate_fpm"
        ]
    ].head(10)
)

/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/prop.py:68: UserWarning: Aircraft: using synonym b77w for b77l
  warnings.warn(

=== OPENAP INPUTS PREPARED ===
Mass estimates available: 88

,plane_id,openap_typecode,estimated_mass_kg,tas_kts,altitude_ft,vertical_rate_fpm
1,710435,A20N,67150.0,462.722025,37400.001197,-64.960630
2,728675,B738,67150.0,464.255388,37275.001193,0.000000
3,70203f,B77W,298775.0,493.556312,37350.001195,0.000000
7,89611b,B77W,298775.0,443.445065,23050.000738,2559.055122
8,89611f,B77W,298775.0,487.822767,32050.001026,0.000000
9,89611e,B77W,298775.0,280.533266,6450.000206,2368.110240
10,896120,B77W,298775.0,493.515783,34150.001093,0.000000
11,8003f3,B738,67150.0,455.162769,38375.001228,0.000000
12,89618b,A388,476000.0,484.749170,38350.001227,0.000000
14,896186,A388,476000.0,495.612164,40475.001295,-64.960630

In [36]:
from openap import FuelFlow

flight_weather["fuel_flow_kg_s"] = np.nan

for idx in flight_weather.index[flight_weather["fuel_flow_ready"]]:
    typecode = flight_weather.at[idx, "openap_typecode"]

    ff = FuelFlow(
        ac=typecode,
        use_synonym=True
    )

    fuel_flow = ff.enroute(
        mass=flight_weather.at[idx, "estimated_mass_kg"],
        tas=flight_weather.at[idx, "tas_kts"],
        alt=flight_weather.at[idx, "altitude_ft"],
        vs=flight_weather.at[idx, "vertical_rate_fpm"]
    )

    flight_weather.at[idx, "fuel_flow_kg_s"] = fuel_flow

print("=== FUEL FLOW RESULTS ===")
print(
    "Fuel-flow estimates:",
    flight_weather["fuel_flow_kg_s"].notna().sum()
)

display(
    flight_weather.loc[
        flight_weather["fuel_flow_ready"],
        [
            "plane_id",
            "openap_typecode",
            "estimated_mass_kg",
            "tas_kts",
            "altitude_ft",
            "vertical_rate_fpm",
            "fuel_flow_kg_s"
        ]
    ].head(10)
)

/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/prop.py:68: UserWarning: Aircraft: using synonym b77w for b77l
  warnings.warn(
/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/drag.py:72: UserWarning: Drag polar: using synonym b77w for b77l
  warnings.warn(
/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/drag.py:72: UserWarning: Drag polar: using synonym b38m for b39m
  warnings.warn(
/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/prop.py:68: UserWarning: Aircraft: using synonym b77w for b77l
  warnings.warn(
/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/drag.py:72: UserWarning: Drag polar: using synonym b77w for b77l
  warnings.warn(
/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/prop.py:68: UserWarning: Aircraft: using synonym b77w for b77l
  warnings.warn(
/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/drag.py:72: UserWarning: Drag polar: using synonym b77w for b77l
  warnings.warn(
/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/prop.py:68: UserWarning: Aircraft: using synonym b77w for b77l
  warnings.warn(
/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/drag.py:72: UserWarning: Drag polar: using synonym b77w for b77l
  warnings.warn(
/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/drag.py:72: UserWarning: Drag polar: using synonym a20n for a21n
  warnings.warn(
/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/prop.py:68: UserWarning: Aircraft: using synonym b77w for b77l
  warnings.warn(
/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/drag.py:72: UserWarning: Drag polar: using synonym b77w for b77l
  warnings.warn(
/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/drag.py:72: UserWarning: Drag polar: using synonym a20n for a21n
  warnings.warn(

=== FUEL FLOW RESULTS ===
Fuel-flow estimates: 88

,plane_id,openap_typecode,estimated_mass_kg,tas_kts,altitude_ft,vertical_rate_fpm,fuel_flow_kg_s
1,710435,A20N,67150.0,462.722025,37400.001197,-64.960630,0.422461
2,728675,B738,67150.0,464.255388,37275.001193,0.000000,0.737201
3,70203f,B77W,298775.0,493.556312,37350.001195,0.000000,3.289003
7,89611b,B77W,298775.0,443.445065,23050.000738,2559.055122,6.116610
8,89611f,B77W,298775.0,487.822767,32050.001026,0.000000,3.474528
9,89611e,B77W,298775.0,280.533266,6450.000206,2368.110240,6.704985
10,896120,B77W,298775.0,493.515783,34150.001093,0.000000,3.407514
11,8003f3,B738,67150.0,455.162769,38375.001228,0.000000,0.724892
12,89618b,A388,476000.0,484.749170,38350.001227,0.000000,4.001043
14,896186,A388,476000.0,495.612164,40475.001295,-64.960630,3.909555

In [37]:
# Test OpenAP fuel-flow results

fuel_results = flight_weather.loc[
    flight_weather["fuel_flow_ready"],
    "fuel_flow_kg_s"
]

assert len(fuel_results) == int(flight_weather["fuel_flow_ready"].sum()), "Fuel-flow result count does not match eligible rows."
assert fuel_results.notna().all(), "Missing fuel-flow estimates found."
assert np.isfinite(fuel_results).all(), "Non-finite fuel-flow values found."
assert (fuel_results > 0).all(), "Non-positive fuel-flow values found."

print("FUEL FLOW TEST: PASS")
print("Fuel-flow observations:", len(fuel_results))
print(
    "Fuel-flow range (kg/s):",
    round(fuel_results.min(), 3),
    "->",
    round(fuel_results.max(), 3)
)
print(
    "Average fuel flow (kg/s):",
    round(fuel_results.mean(), 3)
)

FUEL FLOW TEST: PASS
Fuel-flow observations: 88
Fuel-flow range (kg/s): 0.127 -> 7.546
Average fuel flow (kg/s): 2.458

## 7. Estimate Aircraft Emissions

Estimate aircraft emission rates for observations with valid OpenAP fuel-flow results.

Emissions are calculated only for eligible observations using the aircraft type, fuel-flow estimate, true airspeed, and altitude. Rows without sufficient inputs are retained with unavailable emission estimates.

In [38]:
# Calculate aircraft emission rates using OpenAP

from openap import Emission

emission_cols = [
    "co2_g_s",
    "nox_g_s",
    "co_g_s",
    "hc_g_s",
    "sox_g_s",
    "soot_g_s"
]

# Initialize emission columns
for col in emission_cols:
    flight_weather[col] = np.nan

# Calculate emissions only for fuel-flow-ready observations
for idx in flight_weather.index[flight_weather["fuel_flow_ready"]]:
    typecode = flight_weather.at[idx, "openap_typecode"]

    emission = Emission(
        ac=typecode,
        use_synonym=True
    )

    ff = flight_weather.at[idx, "fuel_flow_kg_s"]
    tas = flight_weather.at[idx, "tas_kts"]
    alt = flight_weather.at[idx, "altitude_ft"]

    flight_weather.at[idx, "co2_g_s"] = emission.co2(ff)
    flight_weather.at[idx, "nox_g_s"] = emission.nox(ff, tas, alt)
    flight_weather.at[idx, "co_g_s"] = emission.co(ff, tas, alt)
    flight_weather.at[idx, "hc_g_s"] = emission.hc(ff, tas, alt)
    flight_weather.at[idx, "sox_g_s"] = emission.sox(ff)
    flight_weather.at[idx, "soot_g_s"] = emission.soot(ff)

print("=== EMISSION RESULTS ===")
print(
    "Emission estimates:",
    flight_weather["co2_g_s"].notna().sum()
)

display(
    flight_weather.loc[
        flight_weather["fuel_flow_ready"],
        [
            "plane_id",
            "openap_typecode",
            "fuel_flow_kg_s",
            "co2_g_s",
            "nox_g_s",
            "co_g_s",
            "hc_g_s",
            "sox_g_s",
            "soot_g_s"
        ]
    ].head(10)
)

/Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/.venv/lib/python3.14/site-packages/openap/prop.py:68: UserWarning: Aircraft: using synonym b77w for b77l
  warnings.warn(

=== EMISSION RESULTS ===
Emission estimates: 88

,plane_id,openap_typecode,fuel_flow_kg_s,co2_g_s,nox_g_s,co_g_s,hc_g_s,sox_g_s,soot_g_s
1,710435,A20N,0.422461,1334.975358,3.741605,3.132395,0.022225,0.506953,0.012674
2,728675,B738,0.737201,2329.554819,9.627139,1.648369,0.145750,0.884641,0.022116
3,70203f,B77W,3.289003,10393.249524,82.253308,4.247047,0.197095,3.946804,0.098670
7,89611b,B77W,6.116610,19328.487959,260.322591,1.160882,0.262257,7.339932,0.183498
8,89611f,B77W,3.474528,10979.506919,88.637417,4.805658,0.191853,4.169433,0.104236
9,89611e,B77W,6.704985,21187.752162,260.257546,1.009326,0.184881,8.045982,0.201150
10,896120,B77W,3.407514,10767.743406,85.994888,4.741252,0.193904,4.089016,0.102225
11,8003f3,B738,0.724892,2290.659605,9.437655,1.659566,0.151182,0.869871,0.021747
12,89618b,A388,4.001043,12643.296072,85.964238,2.787928,0.320129,4.801252,0.120031
14,896186,A388,3.909555,12354.193470,85.735892,1.788001,0.306511,4.691466,0.117287

In [39]:
# Test aircraft emission results

valid_emissions = flight_weather["fuel_flow_ready"]

assert flight_weather.loc[
    valid_emissions, "co2_g_s"
].notna().all(), "Missing CO2 estimates."

assert flight_weather.loc[
    valid_emissions, emission_cols
].ge(0).all().all(), "Negative emission values found."

assert flight_weather.loc[
    ~valid_emissions, emission_cols
].isna().all().all(), "Emissions were calculated for ineligible rows."

assert (
    flight_weather.loc[valid_emissions, emission_cols]
    .notna()
    .all()
    .all()
), "Missing emission estimates found."

print("EMISSION TEST: PASS")
print("Emission observations:", int(valid_emissions.sum()))
print("Rows retained without emissions:", int((~valid_emissions).sum()))

print(
    "CO2 range (g/s):",
    round(flight_weather.loc[valid_emissions, "co2_g_s"].min(), 3),
    "->",
    round(flight_weather.loc[valid_emissions, "co2_g_s"].max(), 3)
)

print(
    "NOx range (g/s):",
    round(flight_weather.loc[valid_emissions, "nox_g_s"].min(), 3),
    "->",
    round(flight_weather.loc[valid_emissions, "nox_g_s"].max(), 3)
)

EMISSION TEST: PASS
Emission observations: 88
Rows retained without emissions: 75
CO2 range (g/s): 399.775 -> 23845.218
NOx range (g/s): 0.557 -> 260.323

## 8. Prepare Final Observation-Level Dataset

Prepare an analysis-ready observation-level dataset that can be appended across repeated pipeline runs.

Each flight observation remains a separate record. The dataset preserves timestamp, position, aircraft, weather, fuel-flow, emissions, and Saudi-boundary information required for future spatiotemporal and traffic analysis.

No traffic corridor or route classification is created from the current single snapshot. These patterns will be derived after observations accumulate across repeated pipeline runs.

In [40]:
# Select analysis-ready observation-level columns

final_columns = [
    # Flight identity and time
    "batch_id",
    "plane_id",
    "flight_id",
    "origin_country",
    "time_position",
    "last_contact",

    # Position and movement
    "longitude",
    "latitude",
    "flight_altitude_m",
    "on_ground",
    "velocity",
    "true_track",
    "vertical_rate",
    "inside_saudi_boundary",

    # Aircraft information
    "registration",
    "manufacturername",
    "model",
    "typecode",
    "openap_typecode",
    "aircraft_metadata_matched",

    # Matched weather
    "weather_time",
    "weather_location_id",
    "weather_latitude",
    "weather_longitude",
    "weather_distance_km",
    "pressure_level_hpa",
    "flight_temperature_c",
    "flight_wind_speed_kmh",
    "flight_wind_direction_deg",

    # Derived flight features
    "headwind_component_ms",
    "crosswind_component_ms",
    "derived_airspeed_ms",

    # Fuel estimation
    "fuel_flow_ready",
    "estimated_mass_kg",
    "fuel_flow_kg_s",

    # Emission estimates
    "co2_g_s",
    "nox_g_s",
    "co_g_s",
    "hc_g_s",
    "sox_g_s",
    "soot_g_s"
]

final_df = flight_weather[final_columns].copy()

print("=== FINAL DATASET STRUCTURE ===")
print("Rows:", len(final_df))
print("Columns:", len(final_df.columns))
print("Duplicate column names:", final_df.columns.duplicated().sum())

display(final_df.head())

=== FINAL DATASET STRUCTURE ===
Rows: 163
Columns: 41
Duplicate column names: 0

,batch_id,plane_id,flight_id,origin_country,time_position,last_contact,longitude,latitude,flight_altitude_m,on_ground,velocity,true_track,vertical_rate,inside_saudi_boundary,registration,manufacturername,model,typecode,openap_typecode,aircraft_metadata_matched,weather_time,weather_location_id,weather_latitude,weather_longitude,weather_distance_km,pressure_level_hpa,flight_temperature_c,flight_wind_speed_kmh,flight_wind_direction_deg,headwind_component_ms,crosswind_component_ms,derived_airspeed_ms,fuel_flow_ready,estimated_mass_kg,fuel_flow_kg_s,co2_g_s,nox_g_s,co_g_s,hc_g_s,sox_g_s,soot_g_s
0,20260920_054121,778823,FYC731,Syrian Arab Republic,2026-09-20 05:41:29+00:00,2026-09-20 05:41:33+00:00,54.3574,24.5961,1508.76,False,121.54,92.67,-2.93,False,NaN,NaN,NaN,NaN,NaN,False,2026-09-20 06:00:00+00:00,0,24.499120,54.423077,12.665532,850,28.5,22.6,261.0,-6.148009,1.269835,115.398978,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20260920_054121,710435,KNE201,Saudi Arabia,2026-09-20 05:40:40+00:00,2026-09-20 05:41:34+00:00,52.3243,22.8661,11399.52,False,235.70,103.76,-0.33,True,HZ-NS23,NaN,NaN,A20N,A20N,True,2026-09-20 06:00:00+00:00,1,22.882248,52.273200,5.534591,250,-41.5,9.4,130.0,2.342036,1.154456,238.044835,True,67150.0,0.422461,1334.975358,3.741605,3.132395,0.022225,0.506953,0.012674
2,20260920_054121,728675,IAW443,Iraq,2026-09-20 05:41:33+00:00,2026-09-20 05:41:33+00:00,50.7521,26.9058,11361.42,False,242.23,113.13,0.00,False,YI-ASU,Boeing,737NG 81Z/W,B738,B738,True,2026-09-20 06:00:00+00:00,2,26.889278,50.787140,3.930537,250,-42.0,31.4,227.0,-3.529559,7.976175,238.833666,True,67150.0,0.737201,2329.554819,9.627139,1.648369,0.145750,0.884641,0.022116
3,20260920_054121,70203f,BBC340,Bangladesh,2026-09-20 05:41:12+00:00,2026-09-20 05:41:12+00:00,55.5674,22.5238,11384.28,False,247.33,67.76,0.00,False,S2-AFP,Boeing,777 3E9ER,B77W,B77W,True,2026-09-20 06:00:00+00:00,3,22.460455,55.585495,7.284837,250,-40.5,24.7,51.0,6.569658,-1.978493,253.907367,True,298775.0,3.289003,10393.249524,82.253308,4.247047,0.197095,3.946804,0.098670
4,20260920_054121,801883,IGO19M,India,2026-09-20 05:41:32+00:00,2026-09-20 05:41:33+00:00,53.1695,24.9630,8808.72,False,232.45,104.22,6.83,False,NaN,NaN,NaN,NaN,NaN,False,2026-09-20 06:00:00+00:00,4,24.991210,53.186222,3.560968,300,-30.5,18.3,238.0,-3.517114,3.670176,228.962304,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
# Audit missing values in the final dataset

null_audit = pd.DataFrame({
    "missing_count": final_df.isna().sum(),
    "missing_percent": (final_df.isna().mean() * 100).round(1)
})

null_audit = null_audit[
    null_audit["missing_count"] > 0
].sort_values("missing_count", ascending=False)

print("=== FINAL DATASET NULL AUDIT ===")
display(null_audit)

=== FINAL DATASET NULL AUDIT ===

                           missing_count  missing_percent
manufacturername                      94             57.7
model                                 87             53.4
nox_g_s                               75             46.0
co_g_s                                75             46.0
hc_g_s                                75             46.0
sox_g_s                               75             46.0
soot_g_s                              75             46.0
fuel_flow_kg_s                        75             46.0
co2_g_s                               75             46.0
estimated_mass_kg                     75             46.0
openap_typecode                       71             43.6
registration                          54             33.1
typecode                              54             33.1
vertical_rate                          8              4.9
flight_id                              6              3.7
flight_altitude_m                      5              3.1
derived_airspeed_ms                    5              3.1
headwind_component_ms                  5              3.1
crosswind_component_ms                 5              3.1
flight_wind_speed_kmh                  5              3.1
flight_temperature_c                   5              3.1
pressure_level_hpa                     5              3.1
flight_wind_direction_deg              5              3.1

In [42]:
# Check Saudi-boundary distribution

print("=== SAUDI BOUNDARY CHECK ===")
print(
    final_df["inside_saudi_boundary"]
    .value_counts(dropna=False)
)

print(
    "\nFuel/emission-ready observations inside Saudi boundary:",
    (
        final_df["inside_saudi_boundary"].fillna(False)
        & final_df["fuel_flow_ready"].fillna(False)
    ).sum()
)

=== SAUDI BOUNDARY CHECK ===
inside_saudi_boundary
False    122
True      41
Name: count, dtype: int64

Fuel/emission-ready observations inside Saudi boundary: 25

In [43]:
# Test final observation-level dataset

assert len(final_df) == len(flight_weather), \
    "Final dataset changed the observation grain."

assert final_df["plane_id"].notna().all(), \
    "Missing plane_id found."

assert final_df["time_position"].notna().all(), \
    "Missing observation timestamp found."

assert final_df["latitude"].notna().all(), \
    "Missing latitude found."

assert final_df["longitude"].notna().all(), \
    "Missing longitude found."

assert final_df["inside_saudi_boundary"].notna().all(), \
    "Missing Saudi-boundary flag found."

assert (
    final_df.loc[
        final_df["fuel_flow_ready"],
        "fuel_flow_kg_s"
    ].notna().all()
), "Fuel-ready observations contain missing fuel-flow estimates."

print("FINAL DATASET TEST: PASS")
print("Observations retained:", len(final_df))
print(
    "Inside Saudi boundary:",
    int(final_df["inside_saudi_boundary"].sum())
)
print(
    "Inside Saudi with emissions:",
    int(
        (
            final_df["inside_saudi_boundary"]
            & final_df["fuel_flow_ready"]
        ).sum()
    )
)

FINAL DATASET TEST: PASS
Observations retained: 163
Inside Saudi boundary: 41
Inside Saudi with emissions: 25

## 9. Transformation Rules and Final Output

Document the transformation rules implemented in Task 4 and verify the final analysis-ready dataset before export.

The rules describe the joins, weather matching, derived flight features, fuel-flow estimation, emission estimation, and preservation of Saudi airspace membership.

Final quality checks are performed before exporting the observation-level dataset to `data/processed/final.csv`.

In [44]:
# Transformation rules implemented in Task 4

rules = pd.DataFrame([
    {
        "Rule ID": "R1",
        "Description": "Join flight observations with aircraft metadata using a left join.",
        "Input Column(s)": "plane_id",
        "Output Column": "aircraft metadata columns"
    },
    {
        "Rule ID": "R2",
        "Description": "Match each flight observation to the nearest available weather location and observation time.",
        "Input Column(s)": "latitude, longitude, time_position",
        "Output Column": "weather_location_id, weather_time, weather_distance_km"
    },
    {
        "Rule ID": "R3",
        "Description": "Select the atmospheric pressure level closest to the aircraft altitude.",
        "Input Column(s)": "flight_altitude_m, geopotential height columns",
        "Output Column": "pressure_level_hpa"
    },
    {
        "Rule ID": "R4",
        "Description": "Select temperature and wind conditions from the altitude-matched pressure level.",
        "Input Column(s)": "pressure_level_hpa, pressure-level weather columns",
        "Output Column": "flight_temperature_c, flight_wind_speed_kmh, flight_wind_direction_deg"
    },
    {
        "Rule ID": "R5",
        "Description": "Derive wind components and air-relative speed from ground velocity, track, and matched wind.",
        "Input Column(s)": "velocity, true_track, flight_wind_speed_kmh, flight_wind_direction_deg",
        "Output Column": "headwind_component_ms, crosswind_component_ms, derived_airspeed_ms"
    },
    {
        "Rule ID": "R6",
        "Description": "Prepare supported observations for OpenAP fuel-flow estimation and estimate aircraft mass from MTOW.",
        "Input Column(s)": "openap_typecode, derived_airspeed_ms, flight_altitude_m, vertical_rate",
        "Output Column": "fuel_flow_ready, estimated_mass_kg"
    },
    {
        "Rule ID": "R7",
        "Description": "Estimate instantaneous aircraft fuel-flow rate using OpenAP.",
        "Input Column(s)": "openap_typecode, estimated_mass_kg, tas_kts, altitude_ft, vertical_rate_fpm",
        "Output Column": "fuel_flow_kg_s"
    },
    {
        "Rule ID": "R8",
        "Description": "Estimate instantaneous aircraft emission rates using OpenAP.",
        "Input Column(s)": "openap_typecode, fuel_flow_kg_s, tas_kts, altitude_ft",
        "Output Column": "co2_g_s, nox_g_s, co_g_s, hc_g_s, sox_g_s, soot_g_s"
    },
    {
        "Rule ID": "R9",
        "Description": "Preserve exact Saudi-boundary membership for downstream Saudi airspace analysis.",
        "Input Column(s)": "inside_saudi_boundary",
        "Output Column": "inside_saudi_boundary"
    }
])

display(rules)

,Rule ID,Description,Input Column(s),Output Column
0,R1,Join flight observations with aircraft metadat...,plane_id,aircraft metadata columns
1,R2,Match each flight observation to the nearest a...,"latitude, longitude, time_position","weather_location_id, weather_time, weather_dis..."
2,R3,Select the atmospheric pressure level closest ...,"flight_altitude_m, geopotential height columns",pressure_level_hpa
3,R4,Select temperature and wind conditions from th...,"pressure_level_hpa, pressure-level weather col...","flight_temperature_c, flight_wind_speed_kmh, f..."
4,R5,Derive wind components and air-relative speed ...,"velocity, true_track, flight_wind_speed_kmh, f...","headwind_component_ms, crosswind_component_ms,..."
5,R6,Prepare supported observations for OpenAP fuel...,"openap_typecode, derived_airspeed_ms, flight_a...","fuel_flow_ready, estimated_mass_kg"
6,R7,Estimate instantaneous aircraft fuel-flow rate...,"openap_typecode, estimated_mass_kg, tas_kts, a...",fuel_flow_kg_s
7,R8,Estimate instantaneous aircraft emission rates...,"openap_typecode, fuel_flow_kg_s, tas_kts, alti...","co2_g_s, nox_g_s, co_g_s, hc_g_s, sox_g_s, soo..."
8,R9,Preserve exact Saudi-boundary membership for d...,inside_saudi_boundary,inside_saudi_boundary

In [45]:
# Edge-case tests required for Task 4

# 1. Empty input should remain empty
empty_input = final_df.iloc[0:0].copy()
assert empty_input.empty, "Empty-input test failed."

# 2. Core observation keys must not be null
assert final_df["plane_id"].notna().all(), \
    "Null plane_id found."

assert final_df["time_position"].notna().all(), \
    "Null time_position found."

# 3. Missing flight_id is allowed and must not remove the observation
assert len(final_df) == len(flight_weather), \
    "Final dataset changed the observation grain."

# 4. Ineligible fuel rows must retain missing estimates
not_fuel_ready = ~final_df["fuel_flow_ready"]

assert final_df.loc[
    not_fuel_ready, "fuel_flow_kg_s"
].isna().all(), \
    "Fuel flow found for an ineligible observation."

print("EDGE-CASE TESTS: PASS")
print("Empty input handled correctly.")
print("Null core keys checked.")
print("Optional missing flight_id retained.")
print("Ineligible fuel rows handled correctly.")

EDGE-CASE TESTS: PASS
Empty input handled correctly.
Null core keys checked.
Optional missing flight_id retained.
Ineligible fuel rows handled correctly.

In [46]:
# Final quality checks before export

assert len(final_df) == len(flight_weather), \
    "Final dataset changed the observation grain."

assert final_df.columns.duplicated().sum() == 0, \
    "Duplicate column names found."

assert final_df["plane_id"].notna().all(), \
    "Missing plane_id found."

assert final_df["time_position"].notna().all(), \
    "Missing time_position found."

assert final_df[["latitude", "longitude"]].notna().all().all(), \
    "Missing flight coordinates found."

assert final_df["inside_saudi_boundary"].notna().all(), \
    "Missing Saudi-boundary flag found."

# Emissions must exist only for eligible observations
emission_cols = [
    "co2_g_s", "nox_g_s", "co_g_s",
    "hc_g_s", "sox_g_s", "soot_g_s"
]

assert final_df.loc[
    final_df["fuel_flow_ready"], emission_cols
].notna().all().all(), \
    "Missing emissions found for eligible observations."

assert final_df.loc[
    ~final_df["fuel_flow_ready"], emission_cols
].isna().all().all(), \
    "Emissions found for ineligible observations."

print("FINAL QUALITY CHECKS: PASS")
print("Rows:", len(final_df))
print("Columns:", len(final_df.columns))
print("Fuel/emission-ready:", int(final_df["fuel_flow_ready"].sum()))
print("Inside Saudi boundary:", int(final_df["inside_saudi_boundary"].sum()))

FINAL QUALITY CHECKS: PASS
Rows: 163
Columns: 41
Fuel/emission-ready: 88
Inside Saudi boundary: 41

In [47]:
# Export the final analysis-ready dataset

final_path = PROCESSED_DIR / "final.csv"

final_df.to_csv(
    final_path,
    index=False
)

print("=== FINAL DATASET EXPORTED ===")
print("Path:", final_path)
print("Rows:", len(final_df))
print("Columns:", len(final_df.columns))

=== FINAL DATASET EXPORTED ===
Path: /Users/noura/Downloads/DataEngineering-bootcamp/DE-SkyPrint/data/processed/final.csv
Rows: 163
Columns: 41

In [48]:
# Verify the exported final dataset

saved_final = pd.read_csv(final_path)

assert len(saved_final) == len(final_df), \
    "Saved file row count does not match final_df."

assert list(saved_final.columns) == list(final_df.columns), \
    "Saved file columns do not match final_df."

assert saved_final["plane_id"].notna().all(), \
    "Saved file contains missing plane_id values."

assert saved_final["time_position"].notna().all(), \
    "Saved file contains missing time_position values."

print("FINAL EXPORT VERIFICATION: PASS")
print("Saved rows:", len(saved_final))
print("Saved columns:", len(saved_final.columns))
print("File:", final_path.name)

FINAL EXPORT VERIFICATION: PASS
Saved rows: 163
Saved columns: 41
File: final.csv

In [49]:
# Test left-join behavior with a null key

left_test = pd.DataFrame({
    "plane_id": ["ABC123", None],
    "observation": ["matched_row", "null_key_row"]
})

right_test = pd.DataFrame({
    "plane_id": ["ABC123"],
    "aircraft_type": ["TEST_TYPE"]
})

result_test = left_test.merge(
    right_test,
    on="plane_id",
    how="left",
    validate="many_to_one"
)

# The left join must preserve both observations
assert len(result_test) == 2, \
    "Left join unexpectedly removed an observation."

# The valid key must match
assert result_test.loc[
    result_test["plane_id"] == "ABC123",
    "aircraft_type"
].iloc[0] == "TEST_TYPE", \
    "Valid key did not match correctly."

# The null key must be retained without a false match
null_row = result_test[result_test["plane_id"].isna()]

assert len(null_row) == 1, \
    "Null-key observation was not retained."

assert null_row["aircraft_type"].isna().all(), \
    "Null key created an unexpected match."

print("NULL-KEY JOIN TEST: PASS")
print("Valid key matched correctly.")
print("Null-key observation retained without a false match.")

NULL-KEY JOIN TEST: PASS
Valid key matched correctly.
Null-key observation retained without a false match.